name: sparks
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  rflutter_alert: ^2.0.2
  permission_handler: ^8.1.4+2
  pin_code_fields: ^7.3.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_analytics: ^8.2.0
  flutter_email_sender: ^5.0.2
  firebase_core: ^1.4.0
  cloud_functions: ^3.0.0
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  timer_builder: ^2.0.0
  liquid_swipe: ^2.1.0
  shared_preferences: ^2.0.6
  flutter_svg: ^0.22.0
  percent_indicator: ^3.0.1
  flutter_rounded_date_picker: ^2.0.2
#  dropdownfield: 1.0.0
  image_picker: ^0.8.2
  image_cropper: ^1.4.1
  badges: ^2.0.1
  flutter_speed_dial: ^4.2.0
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  auto_size_text: ^3.0.0-nullsafety.0
  page_transition: ^2.0.2
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  country_code_picker: ^2.0.2
  flutter_country_state: ^0.2.1
  rxdart: ^0.27.1
  fluttertoast: ^8.0.8
  json_annotation: ^4.0.1
  firebase_messaging: ^10.0.4
  timeago: ^3.1.0
  camera: ^0.8.1+7
  video_player: ^2.1.14
  path_provider: ^2.0.2
  image_stack: ^2.0.1
  readmore: ^2.1.0
  carousel_slider: ^4.0.0
  chewie: ^1.2.2
  agora_rtc_engine: ^4.0.6
  file_picker: ^3.0.4
  video_thumbnail: ^0.3.3
#  modal_progress_hud: ^0.1.3
  modal_progress_hud_alt: ^1.0.0
#  carousel_pro: ^1.0.0
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro.git
      ref: master
#  flutter_material_color_picker: ^1.0.5
  flutter_platform_widgets: ^1.9.5
  visibility_detector: ^0.2.0
  sn_progress_dialog: ^1.0.2
  uuid: ^3.0.4
  pinput: ^1.2.0
  liquid_pull_to_refresh: ^3.0.0
  image_gallery_saver: ^1.6.9
  flutter_downloader: ^1.6.1
  flutter_local_notifications: ^8.0.0 # replaced version 3.0.2
  keyboard_actions: ^3.4.3
  dio: ^4.0.0
  http: ^0.13.3
  stacked: ^2.2.3
  get_it: ^7.2.0
  expandable: ^5.0.1
  intl: ^0.17.0
  encrypt: ^5.0.0
  multi_image_picker: ^4.8.01
  date_format: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  solid_bottom_sheet: ^0.1.10
  flutter_time_picker_spinner: ^2.0.0
  pdf_flutter:
    git: https://github.com/erluxman/pdf_flutter
  flutter_sticky_header: ^0.6.0
#  flutter_custom_dialog: ^1.0.19
  flutter_custom_dialog_tv: ^1.0.20-nullsafety
  url_launcher: ^6.0.9
  device_preview: ^0.7.4
  share: ^2.0.4
  firebase_dynamic_links: ^2.0.7
  open_file: ^3.2.1
  jiffy: ^4.1.0
#  downloads_path_provider: ^0.1.0
  bot_toast: ^4.0.1
  scroll_to_index: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_image_compress: ^1.1.0
  flutter_isolate: ^2.0.0
  shimmer: ^2.0.0
  auto_orientation: ^2.0.2
  sticky_headers: ^0.2.0
  faker: ^2.0.0
  flutter_animated_dialog: ^2.0.1
  better_player: ^0.0.72
  wakelock: ^0.5.2
  volume_control: ^0.1.5
#  flutter_screen_recorder: ^0.0.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  bubble_tab_indicator: ^0.1.6
  flutter_reaction_button: ^1.0.8
  card_swiper: ^1.0.4
  image_downloader: ^0.30.0


#  flutter_reaction_button:
#    git:
#      url: https://github.com/unknownaloy/flutter-reaction-button.git
  flutter_localizations:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/market_images/
    - images/m_registration_images/
    - images/app_entry_and_home/
    - images/app_entry_and_home/post_bg/
    - images/app_entry_and_home/new_images/
    - images/app_entry_and_home/photo_album/
    - images/
    - images/classroom/
    - images/company/
    - images/jobs/
    - images/social/
    

    - images/alumni/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Bold.ttf
    - family: RajdhaniMedium
      fonts:
        - asset: fonts/Rajdhani-Medium.ttf
    - family: Berkshire Swash
      fonts:
        - asset: fonts/BerkshireSwash-Regular.ttf
    - family: NanumGothic
      fonts:
        - asset: fonts/NanumGothic-Regular.ttf
    - family: NanumGothicEB
      fonts:
        - asset: fonts/NanumGothic-ExtraBold.ttf
    - family: NanumGothicB
      fonts:
        - asset: fonts/NanumGothic-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
