import 'dart:collection';

class MarketKeywords {
  /// Keywords for Clothing search
  static HashSet<dynamic> clothingKeyWords = HashSet.from([
    "80s fashion",
    "80's fashion",
    "90s fashion",
    "90's fashion",
    "abaya",
    "african cloth",
    "african clothe",
    "african clothes",
    "african clothings",
    "ao dai",
    "apron",
    "aprons",
    "asian clothing",
    "asian clothings",
    "athletic wear",
    "baby cloth",
    "baby clothe",
    "baby clothes",
    "baby clothing",
    "baby clothing sets",
    "baggy",
    "baggy clothes",
    "ball gown",
    "band t-shirt",
    "band tshirt",
    "bathrobe",
    "bathrobes",
    "beach cloth",
    "beach clothe",
    "beach clothes",
    "beach wear",
    "beach wears",
    "bermuda shorts",
    "biking shorts",
    "bikini",
    "black dress",
    "black dresses",
    "blazers",
    "blouse",
    "bodycon dresses",
    "bouffant gown",
    "bouffant gowns",
    "boxer",
    "boxers",
    "boy's cloths",
    "boys cloths",
    "boy's cloths",
    "boys clothes",
    "boy's jumpers",
    "boys jumpers",
    "bra",
    "bridal sarees",
    "bridal wear",
    "bridalwear",
    "brown pants",
    "brown shirt",
    "brown skirt",
    "brown trouser",
    "camisole",
    "capelet",
    "capes",
    "capri pants",
    "cardigan",
    "cassock",
    "casual wears",
    "charmeuse",
    "cheap clothes",
    "cheap dresses",
    "chemise",
    "cheongsam",
    "christmas clothes",
    "christmas clothing for kids",
    "civilian clothe",
    "civilian clothes",
    "cloth",
    "clothe",
    "cloth item",
    "cloth items",
    "clothe item",
    "clothes",
    "clothes for men",
    "clothes item",
    "clothes shop",
    "clothes shops",
    "clothing for men",
    "clothing store",
    "clothing stores",
    "club wear",
    "clubwear",
    "coat",
    "coat dress",
    "coatdress",
    "coats",
    "cocktail dress",
    "cocktail dresses",
    "collar",
    "collar shirt",
    "corset",
    "costumes",
    "couture",
    "crinoline",
    "culottes",
    "day wear",
    "day wears",
    "debutante dress",
    "denim",
    "denim shorts",
    "denim wear",
    "denim wears",
    "designer",
    "designer men",
    "designer mens",
    "designer women",
    "designer womens",
    "designers",
    "dirndl",
    "dolman sleeve",
    "dress",
    "dress for women",
    "dress for women party wedding",
    "dress online",
    "dress shirt",
    "dress shirts",
    "dress shop",
    "dress shops",
    "dresses",
    "dresses for women",
    "dresses for women party wedding",
    "dresses online",
    "embroidered badges",
    "embroidered patches",
    "evening cloth",
    "evening clothes",
    "evening dress",
    "evening dresses",
    "evening gown",
    "evening gowns",
    "faded jeans",
    "fancy dress",
    "fashion",
    "fashion designer",
    "fashion dress",
    "fashion dresses",
    "fashion style",
    "faux fur coats",
    "feather cloak",
    "female cloth",
    "female clothe",
    "female clothes",
    "fetish lingerie",
    "fetish wear",
    "fetishwear",
    "flare skirt",
    "flared pants",
    "floral dress",
    "floral dresses",
    "floral shirt",
    "floral shirts",
    "flower girl dresses",
    "flowy skirt",
    "flowy skirts",
    "formal cloth",
    "formal clothe",
    "formal clothes",
    "formal dress",
    "formal dresses",
    "formal wear",
    "formal wears",
    "french dress",
    "full dress",
    "fulldress",
    "fur coats",
    "fur shirt",
    "fur skirt",
    "g-string",
    "geek cloth",
    "geek clothe",
    "geek clothes",
    "geek wear",
    "geek wears",
    "girl clothes",
    "girl's cloths",
    "girl's clothes",
    "girls cloths",
    "girls clothes",
    "glass skirt",
    "glass skirts",
    "grass skirt",
    "grass skirts",
    "green pant",
    "green pants",
    "green shirt",
    "green shirts",
    "green skirt",
    "green skirts",
    "gym slip",
    "gymslip",
    "hijab",
    "hoodie",
    "hoods",
    "hoop skirt",
    "hoop skirts",
    "hoopskirt",
    "hoopskirts",
    "iron on patches",
    "jacket",
    "jackets",
    "jeans",
    "jerkin",
    "jersey top",
    "jersey tops",
    "jumper dress",
    "jumpsuit",
    "jumpsuits",
    "kaftan",
    "khaki",
    "kids clothes",
    "kids clothing",
    "kids designer brands",
    "kids designer clothes",
    "kilt",
    "kimono",
    "kirtle",
    "knee length dress",
    "knee length dresses",
    "knitted skirt",
    "knitted skirts",
    "knitwear",
    "ladies dresses",
    "leather cloth",
    "leather clothe",
    "leather clothes",
    "leather jacket",
    "leggings",
    "leotard",
    "lingerie",
    "long sleeves",
    "male cloth",
    "male clothe",
    "male clothes",
    "mandarin collar",
    "maxi dress",
    "maxi dresses",
    "maxi skirt",
    "maxi skirts",
    "men clothes",
    "men jackets",
    "men suits",
    "men's casual wear",
    "men's casual wears",
    "men's clothes",
    "men's gym clothing",
    "men's shirt",
    "men's shirts",
    "men's short-sleeved polo shirts",
    "men's suits",
    "men's tracksuits",
    "mens casual wear",
    "mens casual wears",
    "mens clothes",
    "mens fashion",
    "mens gym clothing",
    "mens jackets",
    "mens shirt",
    "mens shirts",
    "mens short-sleeved polo shirts",
    "mens suits",
    "mens tracksuits",
    "midi skirt",
    "midi skirts",
    "midiskirt",
    "midiskirts",
    "miniskirt",
    "miniskirts",
    "morning dress",
    "muumuu",
    "night dress",
    "nightdress",
    "nightgown",
    "nightwear",
    "outer wear",
    "over garment",
    "over garments",
    "over skirt",
    "over-garment",
    "over-garments",
    "overall",
    "overalls",
    "overdress",
    "overgarment",
    "overskirt",
    "pajamas",
    "pant suit",
    "panties",
    "pantsuit",
    "party dress",
    "party dresses",
    "patches",
    "peignoir",
    "petticoat",
    "pinafore",
    "pinafores",
    "plaid blazers",
    "plaid pants",
    "plaid pantsknee length dress",
    "plain cloth",
    "plain clothe",
    "plain clothes",
    "plain shirt",
    "plainclothes",
    "pleated skirt",
    "pleated skirts",
    "pleated-skirt",
    "pleated-skirts",
    "plus size",
    "plus size dresses",
    "plus size fashion",
    "polo",
    "polo shirt",
    "polo shirts",
    "polonaise",
    "prom dress",
    "prom dresses",
    "puffer jackets",
    "round neck t-shirt",
    "round neck tshirt",
    "round-neck t-shirt",
    "round-neck t-shirts",
    "sailor dress",
    "salopette",
    "salopettes",
    "salwar",
    "saree",
    "satin",
    "sew on patches",
    "sexy dress",
    "sexy dresses",
    "shalwar kameez",
    "sheath dress",
    "sheath dresses",
    "shift dress",
    "shift dresses",
    "shirt",
    "shirt dress",
    "shirts",
    "shorts",
    "singlet",
    "singlets",
    "skate wear",
    "skatewear",
    "ski wear",
    "ski wears",
    "ski-wear",
    "ski-wears",
    "skimpy cloth",
    "skimpy clothe",
    "skimpy clothes",
    "skimpy dress",
    "skinny jean",
    "skinny jeans",
    "skippy dresses",
    "skirt",
    "skirts",
    "skiwear",
    "skiwears",
    "sleeve",
    "sleeveless",
    "sleeves",
    "slip dress",
    "slut wear",
    "slutwear",
    "spaghetti strap",
    "spandex",
    "sports bra",
    "sportswear",
    "stage wear",
    "strapless dress",
    "street cloth",
    "street clothe",
    "street clothes",
    "summer cloth",
    "summer clothes",
    "summer dress",
    "summer dresses",
    "sun dress",
    "sundress",
    "sweater",
    "sweaters",
    "sweatshirt",
    "sweatshirts",
    "swimwear",
    "tailored suit",
    "tailored suits",
    "tea gown",
    "tea gowns",
    "tennis shirt",
    "toga",
    "top",
    "tops",
    "tracksuit",
    "tracksuits",
    "trouser",
    "trousers",
    "tshirt",
    "tutu",
    "tux",
    "tuxedo",
    "tuxedos",
    "tweed jacket",
    "tweed jackets",
    "underclothes",
    "undergarment",
    "uniform",
    "unisex clothing",
    "v-neck",
    "vestiture",
    "vneck",
    "v-neck shirt",
    "v neck shirt",
    "v-neck polo",
    "v neck polo",
    "v-neck vest",
    "v neck vest",
    "waist coat",
    "waistcoat",
    "waterproof top",
    "waterproof tops",
    "wedding dress",
    "women jacket",
    "women's clothes",
    "women's clothing online",
    "women's dress",
    "women's dresses",
    "women's gym clothing",
    "womens clothes",
    "womens fashion",
    "womens jackets",
    "work cloth",
    "work clothe",
    "work clothes",
    "workout top",
    "wrap dress",
  ]);

  static HashSet<dynamic> laptopKeyWords = HashSet.from([
    "11 inch apple mac",
    "11 inch apple mac book",
    "11 inch apple mac book pro",
    "11 inch apple mac books",
    "11 inch apple macbook",
    "11 inch apple macbook pro",
    "11 inch apple macbooks",
    "11 inch chromebook",
    "11 inch chromebooks",
    "11 inch lap top",
    "11 inch lap tops",
    "11 inch laptop",
    "11 inch laptops",
    "11 inch mac book",
    "11 inch mac book pro",
    "11 inch macbook",
    "11 inch macbook pro",
    "11 inch macbooks",
    "11 inch notebook",
    "11 inch notebooks",
    "11 inches apple mac",
    "11 inches apple mac book",
    "11 inches apple mac book pro",
    "11 inches apple macbook",
    "11 inches apple macbook pro",
    "11 inches apple macbooks",
    "11 inches chromebook",
    "11 inches chromebooks",
    "11 inches lap top",
    "11 inches laptop",
    "11 inches mac book pro",
    "11 inches macbook",
    "11 inches macbook pro",
    "11 inches macbooks",
    "11 inches notebook",
    "11 inches notebooks",
    "12 inch apple mac",
    "12 inch apple mac book",
    "12 inch apple mac book pro",
    "12 inch apple mac books",
    "12 inch apple macbook",
    "12 inch apple macbook pro",
    "12 inch apple macbooks",
    "12 inch chromebook",
    "12 inch chromebooks",
    "12 inch lap top",
    "12 inch lap tops",
    "12 inch laptop",
    "12 inch laptops",
    "12 inch mac book",
    "12 inch mac book pro",
    "12 inch macbook",
    "12 inch macbook pro",
    "12 inch macbooks",
    "12 inch notebook",
    "12 inch notebooks",
    "12 inches apple mac",
    "12 inches apple mac book",
    "12 inches apple mac book pro",
    "12 inches apple macbook",
    "12 inches apple macbook pro",
    "12 inches apple macbooks",
    "12 inches chromebook",
    "12 inches chromebooks",
    "12 inches lap top",
    "12 inches laptop",
    "12 inches mac book pro",
    "12 inches macbook",
    "12 inches macbook pro",
    "12 inches macbooks",
    "12 inches notebook",
    "12 inches notebooks",
    "13 inch apple mac",
    "13 inch apple mac book",
    "13 inch apple mac book pro",
    "13 inch apple mac books",
    "13 inch apple macbook",
    "13 inch apple macbook pro",
    "13 inch apple macbooks",
    "13 inch chromebook",
    "13 inch chromebooks",
    "13 inch lap top",
    "13 inch lap tops",
    "13 inch laptop",
    "13 inch laptops",
    "13 inch mac book",
    "13 inch mac book pro",
    "13 inch macbook",
    "13 inch macbook pro",
    "13 inch macbooks",
    "13 inch notebook",
    "13 inch notebooks",
    "13 inches apple mac",
    "13 inches apple mac book",
    "13 inches apple mac book pro",
    "13 inches apple macbook",
    "13 inches apple macbook pro",
    "13 inches apple macbooks",
    "13 inches chromebook",
    "13 inches chromebooks",
    "13 inches lap top",
    "13 inches laptop",
    "13 inches mac book pro",
    "13 inches macbook",
    "13 inches macbook pro",
    "13 inches macbooks",
    "13 inches notebook",
    "13 inches notebooks",
    "14 inch apple mac",
    "14 inch apple mac book",
    "14 inch apple mac book pro",
    "14 inch apple mac books",
    "14 inch apple macbook",
    "14 inch apple macbook pro",
    "14 inch apple macbooks",
    "14 inch chromebook",
    "14 inch chromebooks",
    "14 inch lap top",
    "14 inch lap tops",
    "14 inch laptop",
    "14 inch laptops",
    "14 inch mac book",
    "14 inch mac book pro",
    "14 inch macbook",
    "14 inch macbook pro",
    "14 inch macbooks",
    "14 inch notebook",
    "14 inch notebooks",
    "14 inches apple mac",
    "14 inches apple mac book",
    "14 inches apple mac book pro",
    "14 inches apple macbook",
    "14 inches apple macbook pro",
    "14 inches apple macbooks",
    "14 inches chromebook",
    "14 inches chromebooks",
    "14 inches lap top",
    "14 inches laptop",
    "14 inches mac book pro",
    "14 inches macbook",
    "14 inches macbook pro",
    "14 inches macbooks",
    "14 inches notebook",
    "14 inches notebooks",
    "15 inch apple mac",
    "15 inch apple mac book",
    "15 inch apple mac book pro",
    "15 inch apple mac books",
    "15 inch apple macbook",
    "15 inch apple macbook pro",
    "15 inch apple macbooks",
    "15 inch chromebook",
    "15 inch chromebooks",
    "15 inch lap top",
    "15 inch lap tops",
    "15 inch laptop",
    "15 inch laptops",
    "15 inch mac book",
    "15 inch mac book pro",
    "15 inch macbook",
    "15 inch macbook pro",
    "15 inch macbooks",
    "15 inch notebook",
    "15 inch notebooks",
    "15 inches apple mac",
    "15 inches apple mac book",
    "15 inches apple mac book pro",
    "15 inches apple macbook",
    "15 inches apple macbook pro",
    "15 inches apple macbooks",
    "15 inches chromebook",
    "15 inches chromebooks",
    "15 inches lap top",
    "15 inches laptop",
    "15 inches mac book pro",
    "15 inches macbook",
    "15 inches macbook pro",
    "15 inches macbooks",
    "15 inches notebook",
    "15 inches notebooks",
    "16 inch apple mac",
    "16 inch apple mac book",
    "16 inch apple mac book pro",
    "16 inch apple mac books",
    "16 inch apple macbook",
    "16 inch apple macbook pro",
    "16 inch apple macbooks",
    "16 inch chromebook",
    "16 inch chromebooks",
    "16 inch lap top",
    "16 inch lap tops",
    "16 inch laptop",
    "16 inch laptops",
    "16 inch mac book",
    "16 inch mac book pro",
    "16 inch macbook",
    "16 inch macbook pro",
    "16 inch macbooks",
    "16 inch notebook",
    "16 inch notebooks",
    "16 inches apple mac",
    "16 inches apple mac book",
    "16 inches apple mac book pro",
    "16 inches apple macbook",
    "16 inches apple macbook pro",
    "16 inches apple macbooks",
    "16 inches chromebook",
    "16 inches chromebooks",
    "16 inches lap top",
    "16 inches laptop",
    "16 inches mac book pro",
    "16 inches macbook",
    "16 inches macbook pro",
    "16 inches macbooks",
    "16 inches notebook",
    "16 inches notebooks",
    "17 inch apple mac",
    "17 inch apple mac book",
    "17 inch apple mac book pro",
    "17 inch apple mac books",
    "17 inch apple macbook",
    "17 inch apple macbook pro",
    "17 inch apple macbooks",
    "17 inch chromebook",
    "17 inch chromebooks",
    "17 inch lap top",
    "17 inch lap tops",
    "17 inch laptop",
    "17 inch laptops",
    "17 inch mac book",
    "17 inch mac book pro",
    "17 inch macbook",
    "17 inch macbook pro",
    "17 inch macbooks",
    "17 inch notebook",
    "17 inch notebooks",
    "17 inches apple mac",
    "17 inches apple mac book",
    "17 inches apple mac book pro",
    "17 inches apple macbook",
    "17 inches apple macbook pro",
    "17 inches apple macbooks",
    "17 inches chromebook",
    "17 inches chromebooks",
    "17 inches lap top",
    "17 inches laptop",
    "17 inches mac book pro",
    "17 inches macbook",
    "17 inches macbook pro",
    "17 inches macbooks",
    "17 inches notebook",
    "17 inches notebooks",
    "3d computer graphic",
    "3d computer graphics",
    "3d computer-graphic",
    "3d computer-graphics",
    "3d graphics",
    "3d-computer graphic",
    "3d-computer graphics",
    "3d-computer-graphic",
    "3d-computer-graphics",
    "4k apple mac book pro",
    "4k apple macbook",
    "4k apple macbook pro",
    "4k laptop",
    "4k laptops",
    "4k macbook",
    "4k macbook pro",
    "accelerated processing unit",
    "accelerated processing units",
    "accelerated-processing unit",
    "accelerated-processing units",
    "acer laptop",
    "acer laptops",
    "acer notebook",
    "acer notebooks",
    "alien ware",
    "alien wares",
    "alien-ware",
    "alien-wares",
    "alienware",
    "alienwares",
    "all in one chromebook",
    "all in one chromebooks",
    "all in one desktop",
    "all in one desktops",
    "all in one mac",
    "all in one mac pro",
    "all in one mac pros",
    "all in one macbook pro",
    "all in one macbooks pro",
    "all in one macs",
    "all in one notebook",
    "all in one notebooks",
    "all in one pc",
    "all in one pcs",
    "amd",
    "amd a series",
    "amd a-series",
    "amd a4",
    "amd a6",
    "amd athlon",
    "amd e series",
    "amd e-series",
    "amd hd",
    "amd r5",
    "amd r7",
    "amd radeon",
    "amd radeon hd",
    "amd radeon r5",
    "amd radeon r7",
    "amd turion",
    "analog computer",
    "apple computer",
    "apple computers",
    "apple inc",
    "apple laptop",
    "apple laptops",
    "apple laptops discount",
    "apple mac book pro",
    "apple macbook air",
    "apple macbook pro",
    "arm architecture",
    "asus computer",
    "asus computers",
    "asus laptop",
    "asus laptops",
    "asus notebook",
    "asus notebooks",
    "back lit apple macbook",
    "back lit chromebook",
    "back lit computer",
    "back lit computers",
    "back lit laptop",
    "back lit laptops",
    "back lit mac book",
    "back lit mac book pro",
    "back-lit apple mac book pro",
    "back-lit apple macbooks",
    "back-lit chromebook",
    "back-lit chromebooks",
    "back-lit computer",
    "back-lit computers",
    "back-lit laptop",
    "back-lit laptops",
    "back-lit mac book",
    "back-lit mac book pro",
    "backlit apple mac",
    "backlit apple macbook",
    "backlit chromebook",
    "backlit chromebooks",
    "backlit computer",
    "backlit computers",
    "backlit keyboard",
    "backlit laptop",
    "backlit laptops",
    "backlit mac book",
    "backlit macbook",
    "backlit macbook pro",
    "backlit macbooks",
    "best laptop",
    "best laptops",
    "bio computing",
    "biocomputing",
    "bios",
    "budget chromebook",
    "budget chromebooks",
    "budget computer",
    "budget computers",
    "budget mac book",
    "budget mac book pro",
    "budget mac books",
    "budget macbook",
    "budget macbook pro",
    "budget macbooks",
    "budget notebook",
    "budget notebooks",
    "budget pc",
    "budget pcs",
    "business apple mac book",
    "business apple mac book pro",
    "business apple macbook",
    "business apple macbook pro",
    "business apple macbooks",
    "business chrome book",
    "business chrome books",
    "business chrome-book",
    "business chrome-books",
    "business chromebook",
    "business chromebooks",
    "business computer",
    "business computers",
    "business laptop",
    "business laptops",
    "business mac book",
    "business macbook",
    "business macbooks",
    "cd rom",
    "cd-rom",
    "celeron",
    "celeron processor",
    "celeron processors",
    "central process unit",
    "central processing unit",
    "cheap computer",
    "cheap laptop",
    "cheap laptop computer",
    "cheap laptop computers",
    "cheap laptops",
    "cheapest computer",
    "cheapest computers",
    "chrome book",
    "chrome books",
    "chrome os",
    "chromebook",
    "chromebook for sale",
    "chromebook pixel",
    "chromebooks",
    "cloud storage",
    "code monkey",
    "colored laptop",
    "colored laptops",
    "coloured laptop",
    "coloured laptops",
    "compaq laptop",
    "compaq laptops",
    "computer",
    "computer desktop",
    "computer fan",
    "computer for sale",
    "computer graphic",
    "computer graphics",
    "computer hardware",
    "computer hardwares",
    "computer keyboard",
    "computer monitor",
    "computer monitors",
    "computer notebook",
    "computer pc",
    "computer processor",
    "computer processors",
    "computer screen",
    "computer screens",
    "computer system",
    "computer tech",
    "computers",
    "control computer",
    "core 2 duo",
    "core duo",
    "core i3",
    "core i5",
    "core i7",
    "core i9",
    "core m",
    "cpu",
    "database management system",
    "database management systems",
    "ddr3",
    "ddr3 memory",
    "dedicated computer",
    "dedicated computers",
    "dedicated graphic cards",
    "dedicated graphics card",
    "dell laptop",
    "dell laptop computer",
    "dell laptop computers",
    "dell laptops",
    "dell notebook",
    "dell notebooks",
    "desktop",
    "desktop computer",
    "desktop pc",
    "desktop pcs",
    "digital computer",
    "discount apple mac",
    "discount apple macs",
    "discount chrome book",
    "discount chrome books",
    "discount chrome-book",
    "discount chrome-books",
    "discount chromebook",
    "discount chromebooks",
    "discount laptop",
    "discount laptops",
    "discount mac",
    "discount macs",
    "disk encryption software",
    "disk encryption softwares",
    "drives",
    "dual core",
    "dual core chromebook",
    "dual core chromebooks",
    "dual core computer",
    "dual core computers",
    "dual core laptop",
    "dual core laptops",
    "dual core notebook",
    "dual core notebooks",
    "dynabook",
    "ethernet cable",
    "ethernet cables",
    "fairly used apple mac pro",
    "fairly used apple macbook",
    "fairly used apple macbook pro",
    "fairly used apply mac book",
    "fairly used chromebook",
    "fairly used chromebooks",
    "fairly used lap top",
    "fairly used lap tops",
    "fairly used laptop",
    "fairly used laptops",
    "fairly used mac book",
    "fairly used mac book pro",
    "fairly used macbook",
    "fairly used macbook pro",
    "fairly used notebook",
    "fairly used notebooks",
    "free laptop",
    "free laptop for students",
    "free laptops",
    "gaming computers",
    "gaming desktop",
    "gaming desktops",
    "gaming laptop",
    "gaming laptops",
    "gaming mac",
    "gaming macbook",
    "gaming macbooks",
    "gaming macs",
    "gateway computer",
    "gateway computers",
    "geforce",
    "geforce gt",
    "geforce gtx",
    "geforce nvidia",
    "graphic card",
    "graphic cards",
    "graphics card",
    "hard disk",
    "hard disk drive",
    "hard disk drives",
    "hard disks",
    "hard drive",
    "hard drives",
    "hard-disk",
    "hard-disks",
    "hard-drive",
    "hard-drives",
    "hdmi",
    "hp laptop",
    "hp laptops",
    "hp notebook",
    "hp notebooks",
    "hybrid drive",
    "hybrid hard drive",
    "i3",
    "i5",
    "i7",
    "i9",
    "imac",
    "input device",
    "input devices",
    "integrated computer",
    "integrated computer graphic cards",
    "integrated computer graphics card",
    "integrated computers",
    "integrated graphic cards",
    "integrated graphics card",
    "intel",
    "intel atom",
    "intel celeron",
    "intel core",
    "intel core 2",
    "intel core 2 duo",
    "intel core i3",
    "intel core i5",
    "intel core i7",
    "intel core i9",
    "intel core m",
    "intel duo",
    "intel graphic",
    "intel graphics",
    "intel hd",
    "intel hd graphics",
    "intel i3",
    "intel i5",
    "intel i7",
    "intel i9",
    "intel iris",
    "intel iris graphics",
    "intel iris plus graphics",
    "intel m",
    "intel pentium",
    "intel uhd",
    "intel uhd graphics",
    "intel xeon",
    "lap top",
    "lap top computer",
    "lap top computers",
    "lap tops",
    "laptop",
    "laptop computer",
    "laptop computers",
    "laptop deal",
    "laptop deals",
    "laptop for sale",
    "laptop hardware",
    "laptop hardwares",
    "laptop notebook",
    "laptop notebooks",
    "laptop processor",
    "laptop processors",
    "laptop skin",
    "laptop skins",
    "laptop stand",
    "laptop stands",
    "laptop wireless internet access",
    "laptops",
    "lcd apple mac",
    "lcd apple mac book pro",
    "lcd apple mac book pro screen",
    "lcd apple mac screen",
    "lcd apple macbook",
    "lcd apple macbook pro",
    "lcd apple macbook pro screen",
    "lcd apple macbook screen",
    "lcd apple macbooks",
    "lcd apple macbooks screen",
    "lcd chromebook",
    "lcd chromebook screen",
    "lcd chromebooks",
    "lcd chromebooks screen",
    "lcd lap top",
    "lcd lap top screen",
    "lcd lap tops",
    "lcd lap tops screen",
    "lcd laptop",
    "lcd laptop screen",
    "lcd laptops",
    "lcd laptops screen",
    "lcd mac book pro",
    "lcd mac book pro screen",
    "lcd macbook",
    "lcd macbook pro",
    "lcd macbook pro screen",
    "lcd macbook screen",
    "lcd macbooks",
    "lcd macbooks screen",
    "lcd notebook",
    "lcd notebook screen",
    "lcd notebooks",
    "lcd notebooks screen",
    "led apple mac",
    "led apple mac book pro",
    "led apple mac book pro screen",
    "led apple mac screen",
    "led apple macbook",
    "led apple macbook pro",
    "led apple macbook pro screen",
    "led apple macbook screen",
    "led apple macbooks",
    "led apple macbooks screen",
    "led chromebook",
    "led chromebook screen",
    "led chromebooks",
    "led chromebooks screen",
    "led lap top",
    "led lap top screen",
    "led lap tops",
    "led lap tops screen",
    "led laptop",
    "led laptop screen",
    "led laptops",
    "led laptops screen",
    "led mac book pro",
    "led mac book pro screen",
    "led macbook",
    "led macbook pro",
    "led macbook pro screen",
    "led macbook screen",
    "led macbooks",
    "led macbooks screen",
    "led notebook",
    "led notebook screen",
    "led notebooks",
    "led notebooks screen",
    "legacy port",
    "lenovo chromebook",
    "lenovo chromebooks",
    "lenovo computer",
    "lenovo computers",
    "lenovo desktop",
    "lenovo desktop computer",
    "lenovo desktop computers",
    "lenovo desktops",
    "lenovo laptop",
    "lenovo laptops",
    "lenovo notebook",
    "lenovo notebooks",
    "linux",
    "liquid crystal display",
    "liquid crystal displays",
    "liquid-crystal display",
    "liquid-crystal displays",
    "mac",
    "mac discount",
    "mac for sale",
    "mac os x",
    "mac pro",
    "macbook",
    "macbook air",
    "macbook family",
    "macbook for sale",
    "macbook notebook family",
    "macbook pro",
    "machine code",
    "macintosh",
    "macintosh os",
    "mainframe",
    "mainframe computer",
    "mainframe computers",
    "mainframe laptop",
    "mainframe laptops",
    "mechanical hard drive",
    "memory chip",
    "memory chips",
    "micro sd",
    "micro-sd",
    "microsoft",
    "microsoft surface",
    "microsoft windows",
    "microsoft-windows",
    "mini computer",
    "mini laptop",
    "mini laptops",
    "mini-laptop",
    "mini-laptops",
    "motherboard",
    "motherboards",
    "my computer",
    "nano computer",
    "nano computers",
    "nanocomputer",
    "nanocomputers",
    "net book",
    "net books",
    "net-book",
    "net-books",
    "netbook",
    "netbooks",
    "new apple mac book pro",
    "new apple macbook",
    "new apple macbook pro",
    "new apple macbooks",
    "new chromebook",
    "new chromebooks",
    "new desktop",
    "new desktops",
    "new laptop",
    "new laptops",
    "new mac book",
    "new mac books",
    "new macbook",
    "new macbooks",
    "new notebook",
    "new notebooks",
    "non-volatile memory",
    "note pad",
    "notebook",
    "notebook computer",
    "notebook computers",
    "notebook pc",
    "notebook pcs",
    "notebook processor",
    "notebook processors",
    "notebooks",
    "notepad",
    "nvidia",
    "nvidia geforce",
    "nvidia geforce gt",
    "nvidia geforce gtx",
    "nvidia gt",
    "nvidia gtx",
    "nvidia nvs",
    "nvidia optimus",
    "nvidia quadro",
    "nvidia quadro nvs",
    "operating system",
    "os x",
    "pc",
    "pc card",
    "pc cards",
    "pc computer",
    "pc computers",
    "pci express mini card",
    "pcs",
    "pentium",
    "personal computer",
    "personal computers",
    "pink laptop",
    "pink laptops",
    "portable chrome book",
    "portable chrome books",
    "portable chrome-book",
    "portable chrome-books",
    "portable chromebook",
    "portable chromebooks",
    "portable computer",
    "portable computers",
    "portable lap top",
    "portable lap tops",
    "portable laptop",
    "portable laptops",
    "processor",
    "processors",
    "quad core",
    "quad core chromebook",
    "quad core chromebooks",
    "quad core computer",
    "quad core computers",
    "quad core laptop",
    "quad core laptops",
    "quad core notebook",
    "quad core notebooks",
    "quadro nvs",
    "quanta computer",
    "quantum computer",
    "quantum computers",
    "quantum notebook",
    "quantum notebooks",
    "radeon",
    "radeon hd",
    "radeon r5",
    "radeon r7",
    "ram",
    "random access memory",
    "read only memory",
    "refurb apple mac book",
    "refurb apple mac book pro",
    "refurb apple mac books",
    "refurb apple macbook",
    "refurb apple macbook pro",
    "refurb apple macbooks",
    "refurb chromebook",
    "refurb chromebooks",
    "refurb laptop",
    "refurb laptops",
    "refurb mac book",
    "refurb mac books",
    "refurb mac pro",
    "refurb macbook",
    "refurb macbooks",
    "refurb notebook",
    "refurb notebooks",
    "refurbished laptop",
    "refurbished laptops",
    "rom",
    "second hand apple mac",
    "second hand apple mac book pro",
    "second hand apple mac books",
    "second hand apple macbook",
    "second hand apple macbook pro",
    "second hand chromebook",
    "second hand chromebooks",
    "second hand desktop",
    "second hand desktops",
    "second hand laptop",
    "second hand laptops",
    "second hand mac",
    "second hand mac book",
    "second hand mac book pro",
    "second hand mac books",
    "second hand macbook",
    "second hand mackbooks",
    "second hand macs",
    "second hand notebook",
    "second hand notebooks",
    "secondhand apple mac",
    "secondhand apple mac book pro",
    "secondhand apple macbook",
    "secondhand apple macbook pro",
    "secondhand apple macbooks",
    "secondhand chromebook",
    "secondhand chromebooks",
    "secondhand desktop",
    "secondhand desktops",
    "secondhand laptop",
    "secondhand laptops",
    "secondhand mac",
    "secondhand mac book",
    "secondhand mac books",
    "secondhand macbook",
    "secondhand macbook pro",
    "secondhand macbooks",
    "secondhand macs",
    "secondhand notebook",
    "secondhand notebooks",
    "serial port",
    "servers",
    "single core",
    "single core chromebook",
    "single core chromebooks",
    "single core computer",
    "single core computers",
    "single core laptop",
    "single core laptops",
    "single core notebook",
    "single core notebooks",
    "software",
    "solid state drive",
    "solid state hard drive",
    "sony laptop",
    "sony laptops",
    "sound card",
    "sound cards",
    "sound-card",
    "sound-cards",
    "super computer",
    "super computers",
    "super laptop",
    "super laptops",
    "supercomputer",
    "supercomputers",
    "surface book",
    "surface books",
    "surface-book",
    "surface-books",
    "thinkpad computer",
    "thinkpad computers",
    "thunderbolt",
    "toshiba laptop",
    "toshiba laptops",
    "toshiba notebook",
    "toshiba notebooks",
    "ubuntu",
    "ubuntu computer",
    "ubuntu computers",
    "ubuntu laptop",
    "ubuntu laptops",
    "ubuntu notebook",
    "ubuntu notebooks",
    "uhd graphics",
    "ultra book",
    "ultra books",
    "ultra low voltage processor",
    "ultra low voltage processors",
    "ultra low-voltage processor",
    "ultra low-voltage processors",
    "ultra-low voltage processor",
    "ultra-low voltage processors",
    "ultra-low-voltage processor",
    "ultra-low-voltage processors",
    "ultrabook",
    "ultrabooks",
    "unix",
    "used apple laptop",
    "used apple laptops",
    "used apple mac",
    "used apple macs",
    "used chrome book",
    "used chrome books",
    "used chrome-book",
    "used chrome-books",
    "used chromebook",
    "used chromebooks",
    "used laptop",
    "used laptops",
    "used notebook",
    "used notebooks",
    "v-ram",
    "very cheap laptops",
    "video card",
    "videocard",
    "virtual memory",
    "vram",
    "web server",
    "web servers",
    "windows",
    "windows 10",
    "windows 7",
    "windows 8",
    "windows 8.1",
    "windows rt",
    "wireless internet cards for laptops",
    "work station",
    "work stations",
    "workstation",
    "workstations",
    "xp",
  ]);

  static HashSet<dynamic> phoneKeyWords = HashSet.from([
  "11 pro",
  "11 pro max",
  "2019 apple ipad air",
  "2019 ipad air",
  "2020 apple ipad pro",
  "2020 ipad pro",
  "3g mobile phone",
  "3g mobile phones",
  "3g phone",
  "3g phones",
  "3g smart phone",
  "3g smart phones",
  "3g smart-phone",
  "3g smart-phones",
  "3g smartphone",
  "3g smartphones",
  "5g mobile phone",
  "5g mobile phones",
  "5g phone",
  "5g phones",
  "5g smart phone",
  "5g smart phones",
  "5g smart-phone",
  "5g smart-phones",
  "5g smartphone",
  "5g smartphones",
  "7 in pbs playtime tablet",
  "7 in pbs tablet",
  "7 inch pbs playtime tablet",
  "7 inch pbs tablet",
  "7 inch pbs tablet for kids",
  "7-inch pbs playtime tablet",
  "7-inch pbs tablet",
  "7-inch pbs tablet for kids",
  "amazon fire 7",
  "amazon fire 7 edition",
  "amazon fire 7 edition 2019",
  "amazon fire 7 kids edition",
  "amazon fire 7 kids edition 2019",
  "amazon fire hd",
  "amazon fire hd 10",
  "amazon fire hd 10 2019",
  "amazon fire hd 10 kids",
  "amazon fire hd 10 kids edition",
  "amazon fire hd 10 kids edition 2019",
  "amazon fire hd 8",
  "amazon fire hd 8 16gb",
  "amazon fire hd 8 2020",
  "amazon fire hd10",
  "amazon fire hd10 2019",
  "amazon fire hd8",
  "amazon fire hd8 2020",
  "amazon fire tablet",
  "amazon fire tablets",
  "android",
  "android os",
  "android tablet",
  "android tablets",
  "apple 11",
  "apple 11 pro",
  "apple 11 pro max",
  "apple ipad",
  "apple ipad 2020",
  "apple ipad air",
  "apple ipad air 10.5 inch tablet",
  "apple ipad air 10.5-inch wi-fi 64gb tablet",
  "apple ipad air 2019",
  "apple ipad air tablet",
  "apple ipad mini",
  "apple ipad mini tablet",
  "apple ipad mini wi-fi 64gb tablet",
  "apple ipad mini wi-fi tablet",
  "apple ipad mini wifi 64gb tablet",
  "apple ipad mini wifi tablet",
  "apple ipad pro",
  "apple ipad pro 2020",
  "apple ipad tablet",
  "apple iphone",
  "apple iphone 11",
  "apple iphone 11 pro",
  "apple iphone 11 pro max",
  "apple iphone 12",
  "apple iphone 8",
  "apple iphone 8 +",
  "apple iphone 8 plus",
  "apple iphone 8+",
  "apple iphone x",
  "apple iphone xr",
  "apple iphone xs",
  "apple iphone xs max",
  "apple mini tablet",
  "apple phone",
  "apple phones",
  "apple tablet",
  "asus zenfone 6",
  "asus zenfone 6 unlocked",
  "bell 16 gb tablet",
  "bell 16gb tablet",
  "bell 7 in disney tablet",
  "bell 7 in tablet",
  "bell 7 inch disney tablet",
  "bell 7 inch tablet",
  "bell 7-inch disney tablet",
  "bell 7-inch tablet",
  "best cell phone",
  "best cell-phone",
  "best cellphone",
  "best phone",
  "blackberry",
  "blade 10 prime",
  "blu cell",
  "blu cell phone",
  "blu cell phones",
  "blu cell-phone",
  "blu cell-phones",
  "blu cellphone",
  "blu cellphones",
  "blu cells",
  "blu mobile phone",
  "blu mobile phones",
  "blu mobile-phone",
  "blu mobile-phones",
  "blu mobilephone",
  "blu mobilephones",
  "blu phone",
  "blu phones",
  "blu smart phone",
  "blu smart phones",
  "blu smart-phone",
  "blu smart-phones",
  "blu smartphone",
  "blu smartphones",
  "call",
  "call up",
  "call-up",
  "camera phone",
  "cell phone",
  "cell phones",
  "cell-phone",
  "cell-phones",
  "cellphone",
  "cellphones",
  "cellular phone",
  "cheap phones",
  "compare phones",
  "costco cell phone",
  "dial phone",
  "dial telephone",
  "dial tone",
  "dial-phone",
  "dial-tone",
  "disney edition tablet",
  "disney tablet",
  "feature phone",
  "find x2",
  "find x2 pro",
  "fire hd 10",
  "fire hd 10 2019",
  "fire hd 10 kids",
  "fire hd 10 kids edition",
  "fire hd 10 kids edition 2019",
  "fire hd 8",
  "fire hd 8 2020",
  "first cell phone",
  "flip phone",
  "fone",
  "free cell phone",
  "free cell phones",
  "free cell-phone",
  "free cell-phones",
  "free cellphone",
  "free cellphones",
  "free phones",
  "g pad 10.1",
  "g pad 5",
  "galaxy 9.7 tablet",
  "galaxy a01",
  "galaxy a10s",
  "galaxy a10s 128 gb",
  "galaxy a10s 128gb",
  "galaxy a10s 256 gb",
  "galaxy a10s 256gb",
  "galaxy a10s 64 gb",
  "galaxy a10s 64gb",
  "galaxy a10s unlocked",
  "galaxy a40",
  "galaxy a40 128 gb",
  "galaxy a40 128gb",
  "galaxy a40 256 gb",
  "galaxy a40 256gb",
  "galaxy a40 64 gb",
  "galaxy a40 64gb",
  "galaxy a40 unlocked",
  "galaxy a51",
  "galaxy a51 128 gb",
  "galaxy a51 128gb",
  "galaxy a51 256 gb",
  "galaxy a51 256gb",
  "galaxy a51 64 gb",
  "galaxy a51 64gb",
  "galaxy a51 unlocked",
  "galaxy fold",
  "galaxy fold 2",
  "galaxy fold-2",
  "galaxy fold2",
  "galaxy j2 core",
  "galaxy j2 core unlocked",
  "galaxy note 20",
  "galaxy note 9",
  "galaxy note 9 128 gb",
  "galaxy note 9 128 gb unlocked",
  "galaxy note 9 128gb",
  "galaxy note 9 128gb unlocked",
  "galaxy note 9 256 gb",
  "galaxy note 9 256 gb unlocked",
  "galaxy note 9 256gb",
  "galaxy note 9 256gb unlocked",
  "galaxy note 9 512 gb",
  "galaxy note 9 512 gb unlocked",
  "galaxy note 9 512gb",
  "galaxy note 9 512gb unlocked",
  "galaxy note 9 unlocked",
  "galaxy s10",
  "galaxy s10 plus",
  "galaxy s10+",
  "galaxy s10e",
  "galaxy s10e 128 gb",
  "galaxy s10e 128 gb unlocked",
  "galaxy s10e 128gb",
  "galaxy s10e 128gb unlocked",
  "galaxy s10e 256 gb",
  "galaxy s10e 256 gb unlocked",
  "galaxy s10e 256gb",
  "galaxy s10e 256gb unlocked",
  "galaxy s20",
  "galaxy s20 +",
  "galaxy s20 plus",
  "galaxy s20 ultra",
  "galaxy s20+",
  "galaxy s20plus",
  "galaxy s9",
  "galaxy tab 1",
  "galaxy tab 1 8.0",
  "galaxy tab 8 0",
  "galaxy tab 8.0",
  "galaxy tab 80",
  "galaxy tab a 8 0",
  "galaxy tab a 8.0",
  "galaxy tab a 80",
  "galaxy tab s2",
  "galaxy tab s2 9.7 inch 32 gb tablet",
  "galaxy tab s2 9.7 inch 32gb tablet",
  "google 3a",
  "google cell phone",
  "google cell phones",
  "google cell-phone",
  "google cell-phones",
  "google cellphone",
  "google cellphones",
  "google mobile phone",
  "google mobile phones",
  "google phone",
  "google phones",
  "google pixel 3a",
  "google pixel 4",
  "google pixel 4 64gb unlocked",
  "google pixel 4 xl",
  "google pixel 4xl",
  "google smart phone",
  "google smart phones",
  "google smart-phone",
  "google smart-phones",
  "google smartphone",
  "google smartphones",
  "gophone",
  "hand set",
  "hand-set",
  "handset",
  "huawei cell phone",
  "huawei cell phones",
  "huawei cell-phone",
  "huawei cell-phones",
  "huawei cellphone",
  "huawei cellphones",
  "huawei mate 20",
  "huawei mate 20 pro",
  "huawei mate 20 pro unlocked",
  "huawei mate 20 unlocked",
  "huawei mobile phone",
  "huawei mobile phones",
  "huawei mobile-phone",
  "huawei p20 lite",
  "huawei p30",
  "huawei p30 pro",
  "huawei p30 pro unlocked",
  "huawei p30 unlocked",
  "huawei p40 pro",
  "huawei p40 pro +",
  "huawei p40 pro plus",
  "huawei p40 pro+",
  "huawei phone",
  "huawei phones",
  "huawei smart phone",
  "huawei smart-phone",
  "huawei smartphone",
  "ios",
  "ipad",
  "ipad 2019",
  "ipad 2020",
  "ipad air",
  "ipad air 10.5",
  "ipad air 10.5 tablet",
  "ipad air 10.5-inch wi-fi tablet",
  "ipad air 2019",
  "ipad air wi-fi",
  "ipad air wifi",
  "ipad for kids",
  "ipad mini",
  "ipad mini tablet",
  "ipad mini wi-fi 64gb tablet",
  "ipad mini wi-fi tablet",
  "ipad mini wifi 64gb tablet",
  "ipad mini wifi tablet",
  "ipad os",
  "ipad pro",
  "ipad tablet",
  "ipados",
  "iphone",
  "iphone 11",
  "iphone 11 256 gb",
  "iphone 11 256gb",
  "iphone 11 pro",
  "iphone 11 pro max",
  "iphone 12",
  "iphone 6",
  "iphone 6 plus",
  "iphone 6s",
  "iphone 6s unlocked",
  "iphone 7",
  "iphone 8",
  "iphone 8 plus",
  "iphone se",
  "iphone se 2",
  "iphone se 2020",
  "iphone x",
  "iphone xr",
  "iphone xs",
  "iphone xs max",
  "iphone8",
  "kids ipad",
  "kids tablet",
  "kids tablet pbs",
  "landline",
  "latest cell phone",
  "latest cellphone",
  "latest iphone",
  "latest mobile",
  "latest mobile phone",
  "latest mobile phones",
  "latest samsung phone",
  "latest xiaomi mobile phone",
  "latest xiaomi mobile phones",
  "latest xiaomi phone",
  "latest xiaomi phones",
  "lenovo cell phone",
  "lenovo cell phones",
  "lenovo cell-phone",
  "lenovo cell-phones",
  "lenovo cellphone",
  "lenovo cellphones",
  "lenovo mobile phone",
  "lenovo mobile phones",
  "lenovo phone",
  "lenovo phones",
  "lenovo smart phone",
  "lenovo smart phones",
  "lenovo smart-phone",
  "lenovo smart-phones",
  "lenovo smartphone",
  "lenovo smartphones",
  "lenovo yoga smart tab",
  "lenovo yoga tab",
  "lg cell phone",
  "lg cell phones",
  "lg cell-phone",
  "lg cell-phones",
  "lg cellphone",
  "lg cellphones",
  "lg g pad 10.1",
  "lg g pad 5",
  "lg g pad 5 10.1",
  "lg mobile phone",
  "lg mobile phones",
  "lg phone",
  "lg phones",
  "lg smart phone",
  "lg smart phones",
  "lg smart-phone",
  "lg smart-phones",
  "lg smartphone",
  "lg smartphones",
  "lg v60 5g thinq",
  "mini tablet",
  "mini wi-fi 64gb tablet",
  "mini wi-fi tablet",
  "mini wifi 64gb tablet",
  "mini wifi tablet",
  "mobile",
  "mobile device",
  "mobile operating system",
  "mobile phone",
  "mobile phone 3g",
  "mobile phone 5g",
  "mobile phone deals",
  "mobile phones",
  "mobile phones 3g",
  "mobile phones 5g",
  "mobile-phone",
  "moto g power",
  "moto g-power",
  "moto g6",
  "moto g7 power",
  "moto gpower",
  "motorola cell",
  "motorola cell phone",
  "motorola cell phones",
  "motorola cell-phone",
  "motorola cell-phones",
  "motorola cellphone",
  "motorola cellphones",
  "motorola cells",
  "motorola edge",
  "motorola edge plus",
  "motorola mobile phone",
  "motorola mobile phones",
  "motorola mobile-phones",
  "motorola mobilephone",
  "motorola moto g power",
  "motorola moto g-power",
  "motorola phone",
  "motorola phones",
  "motorola smart phone",
  "motorola smart phones",
  "motorola smart-phone",
  "motorola smart-phones",
  "motorola smartphone",
  "motorola smartphones",
  "new cell phone",
  "new cell phones",
  "new cell-phone",
  "new cell-phones",
  "new cellphone",
  "new cellphones",
  "new iphone",
  "new iphones",
  "new mobile",
  "new phones",
  "nokia cell phone",
  "nokia cell phones",
  "nokia cell-phone",
  "nokia cell-phones",
  "nokia cellphone",
  "nokia cellphones",
  "nokia mobile phone",
  "nokia mobile phones",
  "nokia phone",
  "nokia phones",
  "nokia smart phone",
  "nokia smart phones",
  "nokia smart-phone",
  "nokia smart-phones",
  "nokia smartphone",
  "nokia smartphones",
  "note 9",
  "note 9 128 gb",
  "note 9 128 gb unlocked",
  "note 9 128gb",
  "note 9 128gb unlocked",
  "note 9 256 gb",
  "note 9 256 gb unlocked",
  "note 9 256gb",
  "note 9 256gb unlocked",
  "note 9 512 gb",
  "note 9 512 gb unlocked",
  "note 9 512gb",
  "note 9 512gb unlocked",
  "note 9 unlocked",
  "oneplus 6t",
  "oneplus 6t unlocked",
  "oneplus 7",
  "oneplus 7 pro",
  "oneplus 7t",
  "oneplus 7t pro 5g maclaren",
  "oneplus 7t pro 5g maclaren unlocked",
  "oneplus 8",
  "oneplus 8 pro",
  "onn 8 inch",
  "onn 8 inch tablet",
  "onn 8 tablet",
  "onn 8-inch",
  "onn 8-inch tablet",
  "onn tablet",
  "onyx book note 2",
  "onyx book note2",
  "oppo",
  "oppo a5",
  "oppo a9",
  "oppo cell phone",
  "oppo cell phones",
  "oppo cell-phone",
  "oppo cell-phones",
  "oppo cellphone",
  "oppo cellphones",
  "oppo find x",
  "oppo find x2",
  "oppo find x2 pro",
  "oppo mobile phone",
  "oppo mobile phones",
  "oppo mobilephone",
  "oppo phone",
  "oppo phones",
  "oppo smart phone",
  "oppo smart phones",
  "oppo smart-phone",
  "oppo smart-phones",
  "oppo smartphone",
  "oppo smartphones",
  "oppo x2 pro",
  "p30",
  "p30 pro",
  "p40",
  "p40 pro",
  "p40 pro plus",
  "packard bell 16 gb disney edition tablet",
  "packard bell 16gb disney edition tablet",
  "packard bell 7 in 16gb disney edition tablet",
  "packard bell 7 in disney tablet",
  "packard bell 7 inch 16 gb disney edition tablet",
  "packard bell 7 inch disney edition tablet",
  "packard bell 7 inch disney tablet",
  "packard bell 7-inch 16gb disney edition tablet",
  "packard bell 7-inch disney edition tablet",
  "packard bell 7-inch disney tablet",
  "packard bell disney edition tablet",
  "packard bell disney tablet",
  "packard bell tablet",
  "palm os",
  "pbs 16 gb tablet",
  "pbs 16gb tablet",
  "pbs 7 inch tablet",
  "pbs 7-inch tablet",
  "pbs educational tablet",
  "pbs kids 7 in 16gb educational playtime tablet",
  "pbs kids 7 in tablet",
  "pbs kids 7 inch 16gb educational playtime tablet",
  "pbs kids 7-inch 16gb educational playtime tablet",
  "pbs kids 7-inch tablet",
  "pbs kids tablet",
  "pbs play time tablet",
  "pbs playtime tablet",
  "pbs tablet",
  "pbs tablet for kids",
  "pda",
  "phablet",
  "phone",
  "phone 3g",
  "phone 5g",
  "phone camera",
  "phones",
  "phones 3g",
  "phones 5g",
  "pixel 3a",
  "pixel 4",
  "pixel 4xl",
  "prepaid phones",
  "pro p40",
  "pro p40 plus",
  "push button cell phone",
  "push button cellphone",
  "push button telephone",
  "push-button cell phone",
  "push-button cell-phone",
  "push-button cellphone",
  "push-button telephone",
  "radio telephone",
  "radiotelephone",
  "razer phone 2",
  "realme 6 pro",
  "realme 6 pro 128gb",
  "realme 6 pro 128gb unlocked",
  "realme 6 pro 64gb",
  "realme 6 pro 64gb unlocked",
  "realme 6 pro unlocked",
  "realme c2",
  "realme phone",
  "realme phones",
  "red hydrogen",
  "red hydrogen one",
  "redmi 8a",
  "redmi 8a 128 gb",
  "redmi 8a 128 gb unlocked",
  "redmi 8a 128gb",
  "redmi 8a 128gb unlocked",
  "redmi 8a 64 gb",
  "redmi 8a 64 gb unlocked",
  "redmi 8a 64gb",
  "redmi 8a 64gb unlocked",
  "redmi 8a unlocked",
  "redmi cell phone",
  "redmi cell phones",
  "redmi cell-phone",
  "redmi cell-phones",
  "redmi cellphone",
  "redmi cellphones",
  "redmi mobile phone",
  "redmi mobile phones",
  "redmi note 7",
  "redmi note 7 128 gb",
  "redmi note 7 128 gb unlocked",
  "redmi note 7 128gb",
  "redmi note 7 128gb unlocked",
  "redmi note 7 64 gb",
  "redmi note 7 64 gb unlocked",
  "redmi note 7 64gb",
  "redmi note 7 64gb unlocked",
  "redmi note 7 pro",
  "redmi note 7 pro 128 gb",
  "redmi note 7 pro 128 gb unlocked",
  "redmi note 7 pro 128gb",
  "redmi note 7 pro 128gb unlocked",
  "redmi note 7 pro 64 gb",
  "redmi note 7 pro 64 gb unlocked",
  "redmi note 7 pro 64gb",
  "redmi note 7 pro 64gb unlocked",
  "redmi note 7 pro unlocked",
  "redmi note 7 unlocked",
  "redmi note 8",
  "redmi note 8 128 gb",
  "redmi note 8 128gb",
  "redmi note 8 64 gb",
  "redmi note 8 64gb",
  "redmi note 8 pro",
  "redmi note 8 pro 128 gb",
  "redmi note 8 pro 128 gb unlocked",
  "redmi note 8 pro 128gb",
  "redmi note 8 pro 128gb unlocked",
  "redmi note 8 pro 256 gb",
  "redmi note 8 pro 256 gb unlocked",
  "redmi note 8 pro 256gb",
  "redmi note 8 pro 256gb unlocked",
  "redmi note 8 pro 64 gb",
  "redmi note 8 pro 64 gb unlocked",
  "redmi note 8 pro 64gb",
  "redmi note 8 pro 64gb unlocked",
  "redmi note 8t",
  "redmi note 8t 128 gb",
  "redmi note 8t 128gb",
  "redmi note 8t 64 gb",
  "redmi note 8t 64gb",
  "redmi note 9",
  "redmi note 9 128 gb",
  "redmi note 9 128 gb unlocked",
  "redmi note 9 128gb",
  "redmi note 9 128gb unlocked",
  "redmi note 9 64 gb",
  "redmi note 9 64 gb unlocked",
  "redmi note 9 64gb",
  "redmi note 9 64gb unlocked",
  "redmi note 9 pro",
  "redmi note 9 pro 128 gb",
  "redmi note 9 pro 128 gb unlocked",
  "redmi note 9 pro 128gb",
  "redmi note 9 pro 128gb unlocked",
  "redmi note 9 pro 64 gb",
  "redmi note 9 pro 64 gb unlocked",
  "redmi note 9 pro 64gb",
  "redmi note 9 pro 64gb unlocked",
  "redmi note 9 pro max",
  "redmi note 9 pro max 128 gb",
  "redmi note 9 pro max 128 gb unlocked",
  "redmi note 9 pro max 128gb",
  "redmi note 9 pro max 128gb unlocked",
  "redmi note 9 pro max 64 gb",
  "redmi note 9 pro max 64 gb unlocked",
  "redmi note 9 pro max 64gb",
  "redmi note 9 pro max 64gb unlocked",
  "redmi note 9 pro max unlocked",
  "redmi note 9 pro unlocked",
  "redmi note 9 unlocked",
  "redmi note 9s",
  "redmi note 9s 128 gb",
  "redmi note 9s 128 gb unlocked",
  "redmi note 9s 128gb",
  "redmi note 9s 128gb unlocked",
  "redmi note 9s 64 gb",
  "redmi note 9s 64 gb unlocked",
  "redmi note 9s 64gb",
  "redmi note 9s 64gb unlocked",
  "redmi note 9s unlocked",
  "redmi phone",
  "redmi phones",
  "redmi smart phone",
  "redmi smart phones",
  "redmi smart-phone",
  "redmi smart-phones",
  "redmi smartphone",
  "redmi smartphones",
  "rotary phone",
  "s10e",
  "s20",
  "s20 +",
  "s20 plus",
  "s20 ultra",
  "s20+",
  "s20-plus",
  "s20plus",
  "s9",
  "s9 +",
  "s9 plus",
  "s9+",
  "samsung cell phone",
  "samsung cell phones",
  "samsung cell-phone",
  "samsung cell-phones",
  "samsung cellphone",
  "samsung cellphones",
  "samsung galaxy 9.7 tablet",
  "samsung galaxy a01",
  "samsung galaxy a01 unlocked",
  "samsung galaxy a10s",
  "samsung galaxy a10s 128 gb",
  "samsung galaxy a10s 128gb",
  "samsung galaxy a10s 256 gb",
  "samsung galaxy a10s 256gb",
  "samsung galaxy a10s 64 gb",
  "samsung galaxy a10s 64gb",
  "samsung galaxy a10s unlocked",
  "samsung galaxy a40",
  "samsung galaxy a40 128 gb",
  "samsung galaxy a40 128gb",
  "samsung galaxy a40 256 gb",
  "samsung galaxy a40 256gb",
  "samsung galaxy a40 64 gb",
  "samsung galaxy a40 64gb",
  "samsung galaxy a40 unlocked",
  "samsung galaxy a50 32gb unlocked",
  "samsung galaxy a50 32gb unlocked smartphone",
  "samsung galaxy a51",
  "samsung galaxy a51 128 gb",
  "samsung galaxy a51 128gb",
  "samsung galaxy a51 256 gb",
  "samsung galaxy a51 256gb",
  "samsung galaxy a51 64 gb",
  "samsung galaxy a51 64gb",
  "samsung galaxy a51 unlocked",
  "samsung galaxy fold",
  "samsung galaxy fold 2",
  "samsung galaxy fold2",
  "samsung galaxy j2 core",
  "samsung galaxy j2 core unlocked",
  "samsung galaxy note 20",
  "samsung galaxy note 9",
  "samsung galaxy note 9 128 gb",
  "samsung galaxy note 9 128 gb unlocked",
  "samsung galaxy note 9 128gb",
  "samsung galaxy note 9 128gb unlocked",
  "samsung galaxy note 9 256 gb",
  "samsung galaxy note 9 256 gb unlocked",
  "samsung galaxy note 9 256gb",
  "samsung galaxy note 9 256gb unlocked",
  "samsung galaxy note 9 512 gb",
  "samsung galaxy note 9 512 gb unlocked",
  "samsung galaxy note 9 512gb",
  "samsung galaxy note 9 512gb unlocked",
  "samsung galaxy note 9 64 gb",
  "samsung galaxy note 9 64gb",
  "samsung galaxy note 9 unlocked",
  "samsung galaxy s series",
  "samsung galaxy s-series",
  "samsung galaxy s10e",
  "samsung galaxy s10e 128 gb",
  "samsung galaxy s10e 128 gb unlocked",
  "samsung galaxy s10e 128gb",
  "samsung galaxy s10e 128gb unlocked",
  "samsung galaxy s10e 256 gb",
  "samsung galaxy s10e 256 gb unlocked",
  "samsung galaxy s10e 256gb",
  "samsung galaxy s10e 256gb unlocked",
  "samsung galaxy s20",
  "samsung galaxy s20 +",
  "samsung galaxy s20 + 128gb unlocked",
  "samsung galaxy s20 + unlocked",
  "samsung galaxy s20 plus",
  "samsung galaxy s20 plus 128gb unlocked",
  "samsung galaxy s20 plus unlocked",
  "samsung galaxy s20 ultra",
  "samsung galaxy s20+",
  "samsung galaxy s20+ 128gb unlocked",
  "samsung galaxy s20+ unlocked",
  "samsung galaxy s20plus",
  "samsung galaxy s20plus 128gb unlocked",
  "samsung galaxy s20plus unlocked",
  "samsung galaxy tab 1",
  "samsung galaxy tab 1 8.0",
  "samsung galaxy tab 8 0",
  "samsung galaxy tab 8.0",
  "samsung galaxy tab 80",
  "samsung galaxy tab a 8 0",
  "samsung galaxy tab a 8.0",
  "samsung galaxy tab a 80",
  "samsung galaxy tab s2",
  "samsung galaxy tab s2 9.7 inch 32 gb tablet",
  "samsung galaxy tab s2 9.7 inch 32gb tablet",
  "samsung mobile phone",
  "samsung mobile phones",
  "samsung mobilephone",
  "samsung mobilephones",
  "samsung phone",
  "samsung phones",
  "samsung s2 tablet",
  "samsung s20 ultra",
  "samsung smart phones",
  "samsung smartphone",
  "samsung tab 8 0",
  "samsung tab 8.0",
  "samsung tab 80",
  "samsung tab a",
  "samsung tab a 8.0",
  "samsung tablet",
  "smart phone",
  "smart phone 3g",
  "smart phone 5g",
  "smart phones 3g",
  "smart phones 5g",
  "smart-phone",
  "smart-phone 3g",
  "smart-phone 5g",
  "smart-phones 3g",
  "smart-phones 5g",
  "smartphone",
  "smartphone 3g",
  "smartphone 5g",
  "smartphones 3g",
  "smartphones 5g",
  "sony cell phone",
  "sony cell phones",
  "sony cell-phone",
  "sony cell-phones",
  "sony cellphone",
  "sony cellphones",
  "sony mobile phone",
  "sony mobile phones",
  "sony phone",
  "sony phones",
  "sony smart phone",
  "sony smart phones",
  "sony smart-phone",
  "sony smart-phones",
  "sony smartphone",
  "sony smartphones",
  "sony xperia",
  "sony xperia 1",
  "sony xperia 1 ii",
  "sony xz3",
  "sony xz3 premium",
  "speakerphone",
  "sprint cell phone",
  "sprint mobile phone",
  "sprint mobile-phone",
  "sprint mobile-phones",
  "sprint mobilephone",
  "sprint phones",
  "symbian",
  "t mobile cell phone",
  "t mobile cell phones",
  "t mobile cell-phone",
  "t mobile cell-phones",
  "t mobile phones",
  "t-mobile cell phones",
  "t-mobile cell-phones",
  "tablet",
  "tablet for kids",
  "telephone",
  "telephone call",
  "telephone receiver",
  "tmobile phones",
  "unlock phone",
  "unlocked phone",
  "unlocked phones",
  "used cell phone",
  "used cell phones",
  "used cell-phones",
  "v60 5g thinq",
  "verizon cell phone",
  "verizon phones",
  "vivo cell phone",
  "vivo cell phones",
  "vivo cell-phone",
  "vivo cell-phones",
  "vivo cellphone",
  "vivo cellphones",
  "vivo mobile phone",
  "vivo mobile phones",
  "vivo nex",
  "vivo phone",
  "vivo phones",
  "vivo smart phone",
  "vivo smart phones",
  "vivo smart-phone",
  "vivo smart-phones",
  "vivo smartphone",
  "vivo smartphones",
  "vivo x21",
  "vivo y93",
  "vivo y93s",
  "voice mail",
  "voice-mail",
  "windows mobile",
  "windows phone",
  "x2 pro",
  "xiaomi phone",
  "xiaomi phones",
  "xiaomi redmi 8a",
  "xiaomi redmi 8a 128 gb",
  "xiaomi redmi 8a 128 gb unlocked",
  "xiaomi redmi 8a 128gb",
  "xiaomi redmi 8a 128gb unlocked",
  "xiaomi redmi 8a 64 gb",
  "xiaomi redmi 8a 64 gb unlocked",
  "xiaomi redmi 8a 64gb",
  "xiaomi redmi 8a 64gb unlocked",
  "xiaomi redmi 8a unlocked",
  "xiaomi redmi note 7",
  "xiaomi redmi note 7 128 gb",
  "xiaomi redmi note 7 128 gb unlocked",
  "xiaomi redmi note 7 128gb",
  "xiaomi redmi note 7 128gb unlocked",
  "xiaomi redmi note 7 64 gb",
  "xiaomi redmi note 7 64 gb unlocked",
  "xiaomi redmi note 7 64gb",
  "xiaomi redmi note 7 64gb unlocked",
  "xiaomi redmi note 7 pro",
  "xiaomi redmi note 7 pro 128 gb",
  "xiaomi redmi note 7 pro 128 gb unlocked",
  "xiaomi redmi note 7 pro 128gb",
  "xiaomi redmi note 7 pro 128gb unlocked",
  "xiaomi redmi note 7 pro 64 gb",
  "xiaomi redmi note 7 pro 64 gb unlocked",
  "xiaomi redmi note 7 pro 64gb",
  "xiaomi redmi note 7 pro 64gb unlocked",
  "xiaomi redmi note 7 pro unlocked",
  "xiaomi redmi note 7 unlocked",
  "xiaomi redmi note 8",
  "xiaomi redmi note 8 128 gb",
  "xiaomi redmi note 8 128gb",
  "xiaomi redmi note 8 64 gb",
  "xiaomi redmi note 8 64gb",
  "xiaomi redmi note 8 pro",
  "xiaomi redmi note 8 pro 128 gb",
  "xiaomi redmi note 8 pro 128 gb unlocked",
  "xiaomi redmi note 8 pro 128gb",
  "xiaomi redmi note 8 pro 128gb unlocked",
  "xiaomi redmi note 8 pro 256 gb",
  "xiaomi redmi note 8 pro 256 gb unlocked",
  "xiaomi redmi note 8 pro 256gb",
  "xiaomi redmi note 8 pro 256gb unlocked",
  "xiaomi redmi note 8 pro 64 gb",
  "xiaomi redmi note 8 pro 64 gb unlocked",
  "xiaomi redmi note 8 pro 64gb",
  "xiaomi redmi note 8 pro 64gb unlocked",
  "xiaomi redmi note 8t",
  "xiaomi redmi note 8t 128 gb",
  "xiaomi redmi note 8t 128gb",
  "xiaomi redmi note 8t 64 gb",
  "xiaomi redmi note 8t 64gb",
  "xiaomi redmi note 9",
  "xiaomi redmi note 9 128 gb",
  "xiaomi redmi note 9 128 gb unlocked",
  "xiaomi redmi note 9 128gb",
  "xiaomi redmi note 9 128gb unlocked",
  "xiaomi redmi note 9 64 gb",
  "xiaomi redmi note 9 64 gb unlocked",
  "xiaomi redmi note 9 64gb",
  "xiaomi redmi note 9 64gb unlocked",
  "xiaomi redmi note 9 pro",
  "xiaomi redmi note 9 pro 128 gb",
  "xiaomi redmi note 9 pro 128 gb unlocked",
  "xiaomi redmi note 9 pro 128gb",
  "xiaomi redmi note 9 pro 128gb unlocked",
  "xiaomi redmi note 9 pro 64 gb",
  "xiaomi redmi note 9 pro 64 gb unlocked",
  "xiaomi redmi note 9 pro 64gb",
  "xiaomi redmi note 9 pro 64gb unlocked",
  "xiaomi redmi note 9 pro max",
  "xiaomi redmi note 9 pro max 128 gb",
  "xiaomi redmi note 9 pro max 128 gb unlocked",
  "xiaomi redmi note 9 pro max 128gb",
  "xiaomi redmi note 9 pro max 128gb unlocked",
  "xiaomi redmi note 9 pro max 64 gb",
  "xiaomi redmi note 9 pro max 64 gb unlocked",
  "xiaomi redmi note 9 pro max 64gb",
  "xiaomi redmi note 9 pro max 64gb unlocked",
  "xiaomi redmi note 9 pro max unlocked",
  "xiaomi redmi note 9 pro unlocked",
  "xiaomi redmi note 9 unlocked",
  "xiaomi redmi note 9s",
  "xiaomi redmi note 9s 128 gb",
  "xiaomi redmi note 9s 128 gb unlocked",
  "xiaomi redmi note 9s 128gb",
  "xiaomi redmi note 9s 128gb unlocked",
  "xiaomi redmi note 9s 64 gb",
  "xiaomi redmi note 9s 64 gb unlocked",
  "xiaomi redmi note 9s 64gb",
  "xiaomi redmi note 9s 64gb unlocked",
  "xiaomi redmi note 9s unlocked",
  "xperia 1 ii",
  "xs max",
  "zte blade 10 prime",
  ]);
}
