const List<String> schoolDepartments = [
  "Accounting",
  "Advanced Computer Science",
  "Aeronautical Engineering",
  "Aeronautics & Astronautics",
  "Aeronautics and Astronautics",
  "Aerospace",
  "African American and African Diaspora Studies",
  "African and African American Studies",
  "African Studies",
  "Africana Studies",
  "Agricultural Sciences",
  "American Sign Language",
  "Ancient History",
  "Ancient Philosophy",
  "Anesthesia",
  "Anesthesiology",
  "Anglo-Saxon, Norse and Celtic",
  "Anthropology",
  "Applied and Computational Mathematics",
  "Applied Arts and Sciences",
  "Applied Landscape Archaeology",
  "Applied Linguistics and Second Language Acquisition",
  "Applied Linguistics for Language Teaching",
  "Applied Mathematics",
  "Applied Physics",
  "Applied Physics and Applied Mathematics",
  "Applied Psychology",
  "Applied Theology",
  "Archaeological Science",
  "Archaeology",
  "Architectural History",
  "Architecture",
  "Area Studies",
  "Art & Art History",
  "Art & Design",
  "Art History",
  "Art History and Archaeology",
  "Art, Film and Visual Studies",
  "Asian and Middle Eastern Cultures",
  "Asian and Middle Eastern Studies",
  "Astronomy and Astrophysics",
  "Astrophysics",
  "Atmospheric, Oceanic and Planetary Physics",
  "Atomic and Laser Physics",
  "Audiology",
  "Autonomous Intelligent Machines",
  "Biochemistry",
  "Biochemistry and Molecular Biophysics",
  "Biodiversity, Conservation and Management",
  "Bioengineering",
  "Biological Sciences",
  "Biology",
  "Biology Engineering",
  "Biomaterial Engineering",
  "Biomaterials and Tissue Engineering",
  "Biomedical and Clinical Sciences",
  "Biomedical Engineering",
  "Biomedical Informatics",
  "Biomedical Sciences",
  "Bioprocessing of New Medicines",
  "Biostatistics",
  "Biotechnology",
  "Brain and Cognitive Sciences",
  "Business",
  "Business Administration",
  "Business Administration and Management",
  "Business Law",
  "Business, Economics and Management",
  "Cancer Biomedicine",
  "Cancer Science",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Cardiovascular Science",
  "Cellular Structural Biology",
  "Chemical and Biomolecular Engineering",
  "Chemical and Physical Biology",
  "Chemical and Systems Biology",
  "Chemical Biology",
  "Chemical Engineering",
  "Chemistry",
  "Chemistry and Biochemistry",
  "Chemistry and Physics",
  "Chemistry/Chemical and Bioengineering",
  "Civil & Environmental Engineering",
  "Civil and Environmental Engineering",
  "Civil Engineering",
  "Civil Engineering and Engineering Mechanics",
  "Civil Law",
  "Classical Archaeology",
  "Classical Languages and Literature",
  "Classics",
  "Classics and Ancient Studies",
  "Clinical and Therapeutic Neuroscience",
  "Clinical Embryology",
  "Clinical Medicine",
  "Clinical Mental Health Counseling",
  "Clinical Neurosciences",
  "Clinical Psychology",
  "Clinical Trials",
  "Cognitive and Evolutionary Anthropology",
  "Cognitive Behavioural Studies",
  "Cognitive Behavioural Therapy",
  "Communication",
  "Communication and Media",
  "Comparative Literature",
  "Comparative Literature and Critical Translation",
  "Comparative Media Studies/Writing",
  "Comparative Medicine",
  "Comparative Social Policy",
  "Comparative Study of Religion",
  "Computational and Neural Systems",
  "Computational Discovery",
  "Computational Sciences and Engineering",
  "Computer Game Development",
  "Computer Information Science",
  "Computer Science",
  "Condensed Matter Physics",
  "Construction Management",
  "Contemporary Chinese Studies",
  "Control and Dynamical Systems",
  "Counselling",
  "Creative Writing",
  "Criminal Justice",
  "Criminology",
  "Culinary Arts",
  "Dance",
  "Data, Systems and Society",
  "Deaf Studies and Deaf Education",
  "Deaf Studies/Deaf Education",
  "Decision, Risk and Operations Division",
  "Dermatology",
  "Design Engineering",
  "Developmental Biology",
  "Dietetics",
  "Digestive and Liver Diseases",
  "Dual Business Administration and Accounting",
  "Earth and Environmental Engineering",
  "Earth and Environmental Sciences",
  "Earth and Planetary Sciences",
  "Earth and Space Sciences",
  "Earth Science",
  "Earth Sciences",
  "Earth System Science",
  "Earth, Atmospheric and Planetary Sciences",
  "Earth, Energy & Environmental Sciences",
  "East Asian Languages and Cultures",
  "East Asian Studies",
  "Ecology and Environmental Biology",
  "Ecology, Evolution and Environmental Biology",
  "Economics",
  "Economics and Business",
  "Economics and Finance",
  "Economics and Social History",
  "Education",
  "Education Studies",
  "Educational Leadership",
  "Electrical and Electronic Engineering",
  "Electrical Engineering",
  "Electrical Engineering & Information Technology",
  "Electrical Engineering and Computer Science",
  "Endocrinology",
  "Energy Resources Engineering",
  "Energy Systems",
  "Engineering",
  "Engineering Science",
  "Engineering Sciences",
  "English",
  "English and Comparative Literature",
  "English and Modern Languages",
  "English Local History",
  "Enterprise Resource Planning",
  "Environmental Engineering",
  "Environmental Health Sciences",
  "Environmental Research",
  "Environmental Science",
  "Environmental Science and Engineering",
  "Environmental Science and Public Policy",
  "Environmental Sciences",
  "Environmental Studies",
  "Epidemiology",
  "Event Planning",
  "Evidence-Based Health Care",
  "Exercise Science",
  "Experiential Business and Entrepreneurship",
  "Experimental Psychology",
  "Family studies",
  "Family Studies",
  "Fashion Merchandising",
  "Film (School of the Arts)",
  "Finance",
  "Finance and Economics",
  "Financial Management",
  "Fine Art",
  "Folklore and Mythology",
  "Food Sciences",
  "Forensic Chemistry",
  "French",
  "French and Italian",
  "French and Romance Philology",
  "Future Propulsion and Power",
  "General Business",
  "General Medicine",
  "Genetics",
  "Genetics and Development",
  "Genomic Medicine and Statistics",
  "Geobiology",
  "Geochemistry",
  "Geographic Information Systems",
  "Geography",
  "Geography and the Environment",
  "Geological Sciences",
  "Geology",
  "Geophysics",
  "Geospatial Engineering",
  "Geospatial Sciences",
  "German Studies",
  "Germanic Languages",
  "Germanic Languages and Literatures",
  "Global and Area Studies",
  "Global Languages",
  "Global Support",
  "Government",
  "Graphic Design",
  "Health",
  "Health and Kinesiology",
  "Health Data Science",
  "Health Policy and Management",
  "Health Research & Policy",
  "Health Sciences and Technology",
  "Healthcare Administration",
  "Hematology",
  "History",
  "History and Literature",
  "History and Modern Languages",
  "History and Philosophy of Science",
  "History and Politics",
  "History and Science",
  "History of Art",
  "History of Art and Architecture",
  "History of Art and Visual Culture",
  "History of Science, Medicine and Technology",
  "Hospitality",
  "Hospitality Administration",
  "Human Development and Regenerative Biology",
  "Human Medicine",
  "Human Resources Management",
  "Human, Social and Political Sciences",
  "Humanities",
  "Humanities & Sciences",
  "Humanities + Engineering/Science",
  "Iberian & Latin American Cultures",
  "Industrial and Systems Engineering",
  "Industrial Engineering",
  "Industrial Engineering & Operations Research",
  "Industrial Technology",
  "Infectious Diseases",
  "Inflammatory and Musculoskeletal Disease",
  "Information and Data Sciences",
  "Information Systems Analysis",
  "Information, Communication and the Social Sciences",
  "Inorganic Chemistry",
  "Inorganic Chemistry for Future Manufacturing",
  "Integrated Immunology",
  "Integrative Biology",
  "Interdisciplinary Bioscience",
  "Interdisciplinary Medical Research ",
  "Interdisciplinary Sciences",
  "Interdisciplinary Studies",
  "International Development",
  "International Health and Tropical Medicine",
  "International Relations",
  "International Wildlife Conservation Practice",
  "Ion Channels and Membrane Transport in Health and Disease",
  "Islamic Art and Architecture",
  "Islamic Studies and History",
  "Italian",
  "Japanese Studies",
  "Jewish Studies",
  "Kinesiology",
  "Korean Studies",
  "Land Economy",
  "Late Antique and Byzantine Studies",
  "Latin American and Iberian Cultures",
  "Latin American Studies",
  "Law",
  "Law and Finance",
  "Leadership",
  "Learning and Teaching",
  "Legal Studies",
  "Linguistics",
  "Linguistics, Philology and Phonetics",
  "Literature",
  "Literature and Arts",
  "Magister Juris",
  "Management",
  "Management & Social Sciences",
  "Management Information Systems",
  "Management Science",
  "Management Sciences & Engineering ",
  "Management Studies",
  "Manufacturing Engineering",
  "Marketing",
  "Marketing and Management",
  "Material Science and Engineering",
  "Materials",
  "Materials Science",
  "Materials Science & Engineering",
  "Materials Science and Engineering",
  "Materials Science and Mechanical Engineering",
  "Mathematical and Computational Finance",
  "Mathematical Modelling and Scientific Computing",
  "Mathematical Sciences",
  "Mathematics",
  "Mathematics and Physics",
  "Mechanical Engineering",
  "Media Arts and Sciences",
  "Medical Anthropology",
  "Medical Biosciences",
  "Medical Engineering and Science",
  "Medical Innovation and Enterprise",
  "Medical Physics",
  "Medical Sciences",
  "Medical Sciences and Engineering",
  "Medicine",
  "Medieval Studies",
  "Microbiology",
  "Microbiology & Immunology",
  "Middle Eastern, South Asian and African Studies",
  "Migration Studies",
  "Modelling for Global Health",
  "Modern and Medieval Languages",
  "Modern Chinese Studies",
  "Modern Languages",
  "Modern South Asian Studies",
  "Modern Statistics and Statistical Machine Learning",
  "Molecular & Cellular Physiology",
  "Molecular and Cellular Biology",
  "Molecular and Cellular Medicine",
  "Molecular Bioengineering",
  "Molecular Cell Biology in Health and Disease",
  "Molecular Medicine",
  "Musculoskeletal Sciences",
  "Music",
  "Music and Theatre Arts",
  "Music Composition",
  "Music Education",
  "Music Performance",
  "Natural Sciences",
  "Natural Sciences & Mathematics",
  "Nature, Society and Environmental Governance",
  "Near Eastern Languages and Civilizations",
  "Nephrology",
  "Neurobiology",
  "Neurological Surgery",
  "Neurology",
  "Neurology & Neurological Sciences",
  "Neuroscience",
  "Neurosurgery",
  "Nuclear Science and Engineering",
  "Nursing",
  "Nutrition",
  "Nutrition, Hospitality & Human Services",
  "Obstetrics & Gynecology",
  "Obstetrics and Gynecology",
  "Oncology",
  "Ophthalmology",
  "Organic Chemistry",
  "Oriental Studies",
  "Orthopaedic Surgery",
  "Orthopedic Surgery",
  "Otolaryngology",
  "Otolaryngology - Head & Neck Surgery",
  "Paediatrics",
  "Particle Physics",
  "Pathology",
  "Pathology and Cell Biology",
  "Pediatrics",
  "Pharmaceutical Sciences",
  "Pharmacology",
  "Philosophical Theology",
  "Philosophy",
  "Philosophy of Physics",
  "Photon Science",
  "Physical and Theoretical Chemistry",
  "Physical Education",
  "Physical Education & Recreation",
  "Physics",
  "Physics and Astronomy",
  "Physiology and Cellular Biophysics",
  "Physiology, Anatomy and Genetics",
  "Plant Sciences",
  "Political Science",
  "Political Theory Research",
  "Politics",
  "Politics Research",
  "Population & Family Health",
  "Population Health",
  "Port and Terminal Management",
  "Practical Ethics",
  "Primary Health Care",
  "Psychiatry",
  "Psychiatry and Behavioral Sciences",
  "Psychological and Behavioural Sciences",
  "Psychological Research",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Pulmonary, Allergy and Critical Care Medicine",
  "Radiation",
  "Radiation Biology",
  "Radiation Oncology",
  "Radiology",
  "Refugee and Forced Migration Studies",
  "Rehabilitation and Regenerative Medicine",
  "Religion",
  "Religious Studies",
  "Rheumatology",
  "Romance Languages and Literatures",
  "Russian and East European Studies",
  "Science, Technology and Society",
  "Slavic",
  "Slavic Languages",
  "Slavic Languages and Literature",
  "Slavic Languages and Literatures",
  "Slavonic Studies",
  "Social Anthropology",
  "Social Data Science",
  "Social Intervention and Policy Evaluation",
  "Social Policy",
  "Social Science of the Internet",
  "Social Studies",
  "Social Work",
  "Socio-Legal Studies",
  "Sociology",
  "Sociology and Demography",
  "Sociology, Social Work and Criminal Justice",
  "Sociomedical Sciences",
  "South Asian Studies",
  "Space Science",
  "Spanish and Latin American Cultures",
  "Special Concentrations",
  "Special Education",
  "Speech and Hearing Science",
  "Speech and Hearing Sciences",
  "Statistical Science",
  "Statistics",
  "Structural Biology",
  "Structural Mechanics",
  "Studio Art",
  "Study of Religions",
  "Surgery",
  "Surgical Sciences",
  "Sustainability, Enterprise and the Environment",
  "Synthesis for Biology and Medicine",
  "Syriac Studies",
  "System-Oriented Natural Sciences",
  "Systems Biology",
  "Teacher Education",
  "Theatre",
  "Theatre and Dance",
  "Theatre and Performance",
  "Theatre, Dance & Media",
  "Theology",
  "Theology and Religion",
  "Theology, Religion and Philosophy of Religion",
  "Theoretical and Computational Chemistry",
  "Theoretical Physics",
  "Tibetan and Himalayan Studies",
  "Traditional China",
  "Traditional East Asia",
  "Translational Health Sciences",
  "Urban Studies and Planning",
  "Urology",
  "Veterinary Medicine",
  "Visual Arts",
  "Visual, Material and Museum Anthropology",
  "Vocology",
  "Water Science, Policy and Management",
  "Wind and Marine Energy Systems and Structures",
  "Women's and Reproductive Health",
  "Women's Gender and Sexuality Studies",
  "Women's, Gender and Sexuality Studies",
  "Women, Gender and Sexuality",
  "World Literatures in English",
  "Writing",
  "Yiddish Studies",
  "Zoology",
];
