//TODO: A list of of high school courses.

const List<String> highSchoolCoursesAsset = [
"3-D Art",
"AP Art History",
"AP Biology",
"AP Calculus AB",
"AP Calculus BC",
"AP Chemistry",
"AP Chinese Language And Culture",
"AP Comparative Government And Politics",
"AP Computer Science A",
"AP Computer Science Principles",
"AP English Language And Composition",
"AP English Literature And Composition",
"AP Environmental Science",
"AP European History",
"AP French Language And Culture",
"AP German Language And Culture",
"AP Human Geography",
"AP Italian Language And Culture",
"AP Japanese Language And Culture",
"AP Latin",
"AP Macroeconomics",
"AP Microeconomics",
"AP Music Theory",
"AP Physics 1: Algebra-Based",
"AP Physics 2: Algebra-Based",
"AP Physics C: Electricity And Magnetism",
"AP Psychology",
"AP Research",
"AP Seminar",
"AP Spanish Language And Culture",
"AP Spanish Literature And Culture",
"AP Statistics",
"AP Studio Art: 2-D Design",
"AP Studio Art: 3-D Design",
"AP Studio Art: Drawing",
"AP United States Government And Politics",
"AP United States History",
"AP World History",
"Accounting",
"Aerobics",
"Agriculture",
"Algebra 1",
"Algebra 2",
"American Sign Language",
"American Literature",
"Ancient Greek",
"Animation",
"App Development",
"Arabic",
"Art History",
"Astronomy",
"Audio Production",
"Auto Body Repair",
"Auto Mechanics",
"Biology",
"Botany",
"British Literature",
"Building Construction",
"Business Law",
"Business Management",
"CPR Training",
"Calculus",
"Ceramics",
"Chemistry",
"Chemistry Of Foods",
"Chinese",
"Choir",
"Communication Skills",
"Computer Math",
"Computer Programming",
"Computer Repair",
"Computer-Aided Drafting",
"Concert Band",
"Consumer Education",
"Consumer Math",
"Contemporary Literature",
"Cosmetology",
"Creative Writing",
"Criminal Justice",
"Culinary Arts",
"Cultural Anthropology",
"Current Events",
"Dance",
"Dance",
"Debate",
"Digital Media",
"Drama",
"Drawing",
"Driver Education",
"Early Childhood Development",
"Early Childhood Education",
"Earth Science",
"Electronics",
"Electronics",
"English Language And Composition",
"English Literature And Composition",
"Entrepreneurial Skills",
"Environmental Science",
"Environmental Studies",
"European History",
"FFA (Future Farmers Of America)",
"Family Studies",
"Fashion And Retail Merchandising",
"Fashion Construction",
"Film Production",
"Film Production",
"Fire Science",
"Forensic Science",
"French",
"Fundamentals Of Math",
"Geography",
"Geology",
"Geometry",
"German",
"Global Studies",
"Graphic Design",
"Guitar",
"Gymnastics",
"Health",
"Heating And Cooling Systems",
"Hebrew",
"Home Economics",
"Hospitality And Tourism",
"Human Geography",
"Humanities",
"Integrated Math",
"Interior Design",
"International Relations",
"Introduction To Business",
"Italian",
"JROTC (Junior Reserve Officers Training Corps)",
"Japanese",
"Jazz Band",
"Jewelry Design",
"Journalism",
"Korean",
"Latin",
"Law",
"Lifeguard Training",
"Literary Analysis",
"Macroeconomics",
"Marching Band",
"Marine Biology",
"Marketing",
"Math & Computer Science",
"Math Applications",
"Media Technology",
"Metalworking",
"Microeconomics",
"Modern Literature",
"Modern World Studies",
"Multivariable Calculus",
"Music Production",
"Music Theory",
"Networking",
"Nutrition",
"Oceanography",
"Orchestra",
"Painting",
"Percussion",
"Personal Finance",
"Photography",
"Physical Anthropology",
"Physical Science",
"Physics",
"Piano",
"Pilates",
"Plumbing",
"Poetry",
"Political Studies",
"Popular Literature",
"Portuguese",
"Practical Math",
"Pre-Algebra",
"Pre-Calculus",
"Printmaking",
"Probability",
"Production Technology",
"Psychology",
"Quantitative Literacy",
"Racket Sports",
"Refrigeration Fundamentals",
"Religious Studies",
"Rhetoric",
"Robotics",
"Russian",
"Sculpture",
"Sociology",
"Spanish",
"Specialized Sports",
"Statistics",
"Swimming",
"Technical Writing",
"Theater Technology",
"Trigonometry",
"Typing",
"US Government",
"US History",
"Video Game Development",
"Web Design",
"Web Programming",
"Weight Training",
"Women's Studies",
"Woodworking",
"Word Processing",
"Works Of Shakespeare",
"World History",
"World Literature",
"World Music",
"World Politics",
"World Religions",
"Written And Oral Communication",
"Yoga",
"Zoology",
];

