//TODO: A list of hobbies.

const List<String> hobbiesAsset = [
"Acrobatics",
"Acroyoga",
"Adventure Running",
"Air Gardening",
"Airbrushing",
"Aircraft Spotting",
"Airplane Combat",
"Airsoft",
"Airsofting",
"Amateur Geology",
"Anagram Designing",
"Animal Craft",
"Anti-Gravity Cocooning",
"Antiquing",
"Aquascaping",
"Archaeology",
"Archery",
"Architecture",
"Art Collecting",
"Arts And Crafts",
"Astrology",
"Astronomy",
"Attend Renaissance Fairs",
"Audiophile",
"Auto Customization",
"Auto Detailing",
"Babysitting",
"Backpacking",
"Badminton",
"Baking",
"Balloon Twisting",
"Ballroom Dancing",
"Barbecuing",
"Bartending",
"Base Jumping",
"Baseball",
"Basketball",
"Baton Twirling",
"Beach / Sand Building",
"Beach Volleyball",
"Beachcombing",
"Beadwork",
"Beat Box",
"Beatboxing",
"Become A Wikipedia Editor",
"Becoming A Film Buff",
"Becoming A Fitness Instructor",
"Becoming A Local Guide",
"Becoming A Rail Fan",
"Becoming An Alcohol Connoisseur",
"Beekeeping",
"Beer Tasting",
"Being A Cigar Aficionado",
"Being A Handyman",
"Being A History Buff",
"Bicycle Polo",
"Bicycling",
"Bird Watching",
"Blacksmithing",
"Board Game Club",
"Board Surfing",
"Boat Making",
"Boat Racing",
"Book Clubs",
"Book Restoration",
"Bookbinding",
"Boomerangs",
"Bouldering",
"Bowling",
"Boxing",
"Break Dancing",
"Brewing Beer",
"Bridge Building",
"Build Model Rockets",
"Building Dollhouses",
"Building Electronics",
"Building Ships In Bottles",
"Building Tesla Coils",
"Butterfly Watching",
"Buying And Selling",
"Cake Decorating",
"Calligraphy",
"Camping",
"Candle Making",
"Canoeing",
"Car Racing",
"Carpet Weaving",
"Cartography",
"Cartooning & Animation",
"Cash Flow Planning",
"Catering",
"Cave Diving",
"Caving",
"Ceramics",
"Chainsaw Carving",
"Chandlery",
"Cheerleading",
"Chocolate Making",
"Chocolate Tasting",
"Circuits Training",
"Cliff Diving",
"Cloud Watching",
"Coaching Local Sports",
"Coding",
"Coffee Roasting",
"Coin Collecting",
"Collage Making",
"Collect Trainers",
"Collecting Baseball Cards",
"Collecting Comic Books",
"Collecting Diecast Cars",
"Collecting Leaves",
"Collecting Marbles",
"Collecting Military Paraphernalia",
"Collecting Model Trains",
"Collecting Sea Glass",
"Collecting Seashells",
"Collecting Stamps",
"Collecting Stickers",
"Color Guard",
"Coloring",
"Comic Book Art",
"Community Activism",
"Competitive Eating",
"Computer Technician",
"Container Gardening",
"Conworlding",
"Cookie Decorating",
"Cooking",
"Cosplaying",
"Couponing",
"Crabbing",
"Create And Sell Gourmet Pet Treats",
"Create Or Sell Pet Clothing",
"Creating And/Or Editing Videos",
"Creating Family Trees",
"Creating Video Tutorials",
"Credit Card Collecting",
"Crocheting",
"Crocheting",
"Croquet",
"Cross Country Running",
"Crossword Puzzles",
"Cryptography",
"Curling",
"D Printing And Physibles",
"Dancing",
"Dandyism",
"Decluttering",
"Decorating Homes",
"Deltiology",
"Digital Scrapbooking",
"Discover Microscopy",
"Distilling",
"Do Improv",
"Dog Sport",
"Dog Training",
"Dog Walking",
"Doing Science Experiments",
"Doll Making",
"Dominoes",
"Drag Boat Racing",
"Dragon Boat Racing",
"Drawing",
"Drive Others Around",
"Drone Flying",
"Dumpster Diving",
"Eggshell Carving",
"Embroidery",
"Engravings",
"Entertaining & Event Hosting",
"Exercising",
"Falconry",
"Fantasy Sports",
"Farming",
"Fell Running",
"Felting",
"Fencing",
"Feng Shui Decorating",
"Field Hockey",
"Financial Planning",
"Finger Painting",
"Fire Poi",
"Firearm Enthusiast",
"Fish Tournaments",
"Fishing",
"Fishkeeping",
"Fitness Or Yoga Trainer",
"Flag Football",
"Flea Market Shopping",
"Flipping Items",
"Floristry",
"Flower Arranging",
"Flower Making",
"Flower Pressing",
"Fly Fishing",
"Fly Tying",
"Flying",
"Flying Drones",
"Flying Model Planes",
"Football",
"Food Preservation (Pickling, Canning)",
"Foraging",
"Fossil Hunting",
"Fostering Animals",
"Found A Charity Group",
"Four Wheeling",
"Freediving",
"Freelance Photography",
"Frisbee Golf – Frolf",
"Fruit Carving",
"Furniture Making",
"Gardening",
"Genealogy",
"Geocaching",
"Ghost Hunting",
"Giving Advice Or Opinions",
"Glass Blowing",
"Glowsticking",
"Gnoming",
"Go Kart Racing",
"Go To Free Community Events",
"Golf",
"Graphic Design",
"Graphology",
"Grilling",
"Grip Strength",
"Growing Bonsais",
"Guerrilla Gardening",
"Gun Collecting",
"Gunsmithing",
"Gymnastics",
"Gyotaku",
"Hang Gliding",
"Helping The Homeless",
"Herping",
"Hiking",
"Home Brewing",
"Home Staging",
"Homesteading",
"Hookah Smoking",
"Horseback Riding",
"Hosting Dinner Parties",
"Hot Air Ballooning",
"Hunting",
"Ice Fishing",
"Impersonations",
"Improving Your Memory",
"Infuse Alcohol",
"Insect Interest",
"Inventing",
"Investing",
"Jam Making",
"Jet Sprint Boat Racing",
"Jewellery Making",
"Jogging/Training For Marathon",
"Journaling",
"Juggling",
"Jump Roping",
"Karate",
"Keep Abreast Of News And Current Affairs",
"Kicksled",
"Kinetic Sculpture Racing",
"Kitchen Chemistry",
"Kite Flying",
"Kitesurfing",
"Knapping",
"Knife Making",
"Knife Throwing",
"Knitting",
"Knotting",
"Lacemaking",
"Lacrosse",
"Lamp Making",
"Landscaping",
"Lapidary",
"Laser Tag",
"Latte Art",
"Leaf Collecting And Pressing",
"Learn About Philosophy",
"Learn How To Make String Figures",
"Learn To Sew",
"Learning A Foreign Language",
"Learning A New Sport",
"Learning How To DIY",
"Learning How To Play Musical Instruments",
"Learning Sign Language",
"Leather Making",
"Leather Tooling",
"Lego Building/Assembling",
"Letterboxing",
"Life Coaching",
"Lockpicking",
"Lomography",
"LudoSport",
"Macrame",
"Magic Tricks & Card Tricks",
"Making Bird Feeders And Birdhouses",
"Making Bookmarks",
"Making Key Holders",
"Making Miniatures",
"Making Model Cars",
"Making Music",
"Making T-Shirts",
"Making Time Capsules",
"Making Your Own Hot Sauce",
"Martial Arts",
"Massage",
"Matchstick Modeling",
"Meditation",
"Metal Detecting",
"Metal Working",
"Meteorology",
"Mini Golf",
"Minimalism",
"Mobile Technician",
"Model Rockets",
"Model Ship Building",
"Motocross",
"Motorcycling",
"Mountain Biking",
"Mountaineering",
"Museum/Art Gallery Hopping",
"Music Memorabilia",
"Music Writing",
"Nature Walk",
"Neuro Linguistic Programming",
"Noodling",
"Offroading",
"Organize A Neighborhood Clean-Up",
"Organize Fundraising",
"Orienteering Sports",
"Origami",
"Outrigger Canoe Racing",
"Paintballing",
"Painting",
"Palm Reading",
"Paper Mache",
"Papermaking",
"Parachuting",
"Paragliding",
"Parkour – Freerunning",
"Participate In Trivia Contests",
"Pencil Carving",
"Pencil Sketching",
"People Watching",
"Performing Stand Up Comedy",
"Pet Grooming",
"Pet Sitting",
"Photography",
"Picnicking",
"Pinochle",
"Pipe Making",
"Plan Walking Tours",
"Playing Chess",
"Playing Darts",
"Playing Pool/Darts/Foosball",
"Playing Soccer",
"Playing T-Ball",
"Playing The Stock Market",
"Podcasting",
"Poetry",
"Poker",
"Polo",
"Pottery",
"Powerboking",
"Practicing Survival Skills",
"Producing Electronic Music",
"Programming",
"Proofreading And Editing",
"Public Speaking",
"Puppet Making",
"Puppetry",
"Pursuing Credit Card Rewards",
"Pyrotechnics",
"Quilling",
"Quilting",
"RC Model Racing",
"RV Travelling",
"Racquetball",
"Raising Animals",
"Rapping",
"Reading",
"Recipe Creation",
"Record Collecting",
"Reef Aquarium",
"Refinishing Furniture",
"Renovating",
"Restoring Furniture",
"Retro Gaming",
"Reviewing Gadgets",
"Reviewing Things",
"River Rafting",
"Road Biking",
"Road Trips",
"Robot Making",
"Rock And Mineral Collecting",
"Rock Balancing",
"Rock Climbing",
"Rock Painting",
"Roller Blading",
"Rugby",
"Running",
"Sailing",
"Salsa Dancing",
"Sand Art",
"Sandboarding",
"Scale Miniature Building",
"Scouting",
"Scrapbooking",
"Screen Printing",
"Scuba Diving",
"Sculling Or Rowing",
"Sculpt With Clay/ Playdough",
"Sculpting",
"Search Engine Marketing",
"Self Defense",
"Self-Care",
"Shark Diving",
"Shell Fishing",
"Shooting/Marksmanship",
"Silver Making",
"Singing",
"Skateboarding",
"Skating",
"Skeet Shooting",
"Skiing/Snowboarding",
"Skijoring",
"Skimboarding",
"Sky Diving",
"Skydiving",
"Slack Lining",
"Slingshots",
"Smoking Meat",
"Snorkeling",
"Snowmobiling",
"Soap Making",
"Social Media",
"Solitaire",
"Solving Mazes",
"Spear Fishing",
"Speed Cubing (Rubix Cube)",
"Speed Reading",
"Speed Skating",
"Sports – Refereeing",
"Squash",
"Stamp Collecting",
"Star Gazing",
"Star Watching",
"Start An Allotment",
"Start Ground Hopping",
"Starting A Band",
"Starting A YouTube Channel",
"Starting An Etsy Or EBay Store",
"Stone Skipping",
"Stone Working",
"Storm Chasing",
"Story-Writing",
"Storytelling",
"Sudoku",
"Surf Fishing",
"Surf Lifesaving",
"Surfing",
"Survival Prepping",
"Sushi Making",
"Swimming",
"Table Tennis",
"Tai Chi",
"Taking Free Online Classes",
"Taking Paid Surveys",
"Taking Part Historical Reenactments",
"Tapestry",
"Tapping Maple Trees",
"Tarot Reading",
"Tatebanko",
"Tatting",
"Tattoo Designing",
"Tattooing",
"Taxidermy",
"Tea Drinking",
"Teaching And Tutoring Music",
"Tennis",
"Tequila Tasting",
"Terrarium Making",
"Theme Night Dates",
"Tomahawk/Hatchet Throwing",
"Tombstone Rubbing",
"Tool Collecting",
"Tour Skating",
"Touring Wineries",
"Tower Running",
"Track Cycling",
"Trail Running",
"Trainspotting",
"Travel Hacking",
"Traveling",
"Treasure Hunting",
"Trekking",
"Tutoring Children",
"Ultimate Frisbee",
"Upcycling",
"Upholstery",
"Urban Exploration",
"Urban Fruit Picking",
"Using Ham Radio",
"Ventriloquism",
"Video Games",
"Vinyl Collecting",
"Volunteering",
"Wakeboarding",
"Walking",
"Wall Art",
"War Gaming",
"Watch Documentaries",
"Watch Making",
"Water Ski",
"Website Optimization",
"Weekend Adventuring",
"Weight Lifting",
"Whale Watching",
"Wheel Throwing",
"Whisky Tasting",
"Whittling",
"Windsurfing",
"Wine Making",
"Wine/Cheese Tasting",
"Wingsuit Flying",
"Woodburning",
"Woodworking",
"Working On Cars",
"Working Out",
"World Record Breaking",
"Wrestling",
"Writing Letters",
"Writing Music",
"Writing/Blogging",
"Yo-Yoing",
"Yoga",
"Ziplining",
"Zoo Visits",
"Zumba",
];
