const Map<String, List<String>> industries = {
  "Agriculture": [
    "Farmer",
    "Agronomist",
    "Agricultural engineer",
    "Farmworker",
    "Geneticist",
    "Plant Biologist",
    "Agricultural Manager",
    "Beekeeper",
    "Agricultural Economist",
    "Biochemist",
    "Forest Scientist",
    "Soil Scientist",
    "Fisherman",
    "Business consultant",
    "Zookeeper",
    "Animal nutritionist",
    "Butcher",
    "Horticulturist",
    "Machinist",
    "Plant Pathologist"
  ],
  "Education": [
    'Teacher',
    'Librarian',
    'School counselor',
    'Author',
    'Technician',
    'Psychologist',
    'Tutor',
    'Curator',
    'Scientist',
    'Accountant',
    'Bursar',
    'Secretary',
    'Information professional',
    'Economist',
    'Employment counsellor',
    'Occupational Therapist',
    'Educational consultant',
    'Technologist',
    'Cleaner',
    'Cashier'
  ],
  "Entertainment": [
    'Actor',
    'Artist',
    'Musician',
    'Makeup Artist',
    'Film director',
    'Performance Artist',
    'Photographer',
    'Audio engineer',
    'Video editor',
    'Comedian',
    'Stunt performer',
    'Camera man',
    'Talent agent',
    'Writer',
    'Art Director',
    'Cinematographer',
    'Screenwriter',
    'Composer',
    'Film Producer',
    'Record producer',
  ],
  "Healthcare": [
    'Health professional',
    'Physician',
    'Registered nurse',
    'Pharmacist',
    'Dentist',
    'Nurse practitioner',
    'Surgeon',
    'Midwife',
    'Dietitian',
    'Paramedic',
    'Surgical technologist',
    'Optometrist',
    'Psychiatrist',
    'Medical Secretary',
    'Technologist',
    'Laboratory Technician',
    'Paediatrician',
    'Emergency medical technician',
    'Respiratory therapist',
    'Radiographer',
  ],
  "Manufacturing": [
    'Mechanical engineer',
    'Engineer',
    'Technician',
    'Labourer',
    'Welder',
    'Machinist',
    'Industrial Engineer',
    'Design Engineer',
    'Woodworker',
    'Materials engineer',
    'Plumber',
    'Civil engineer',
    'Industrial designer',
    'Automotive Engineer',
    'Structural engineer',
    'Fashion designer',
    'Laboratory Technician',
    'Construction worker',
    'Safety engineer',
    'Chemical engineer',
  ],
  "Media": [
    'Journalist',
    'Writer',
    'Photographer',
    'Technical writer',
    'Author',
    'Actor',
    'Copywriter',
    'Proof reader',
    'Analyst',
    'Sports commentator',
    'Television producer',
    'Video Editor',
    'Television presenter',
    'Announcer',
    'News producer',
    'Playwright',
    'Lighting designer',
    'Television director',
    'Radio producer',
    'Multimedia artist',
  ],
  "Technology": [
    'Software Developer',
    'Web designer',
    'Computer systems analyst',
    'Computer hardware engineer',
    'Computer repair technician',
    'Network Engineer',
    'Technolgy specialist',
    'Network administrator',
    'Information technology consultant',
    'Test engineer',
    'Software Engineer',
    'Electrician',
    'Inventor',
    'Industrial Engineer',
    'Physician',
    'Financial Analyst',
    'Civil engineer',
    'Investor',
    'Mechanical engineer',
    'Technical writer',
  ]
};
