List<String> languagesAsset = <String>[
'Abaza – Aбаза бызшва',
'Abellen – Ayta Abellen',
'Abenaki † – Alnôba, Wôbanakiôdwawôgan',
'Abkhaz – Aҧсуа бызшәа, Aҧсшәа',
'Adangbe – Adangbe',
'Adangme – Adangbɛ',
'Adyghe – Адыгэбзэ',
'Afar – Qafár af',
'Afrikaans',
'Ainu – アイヌ イタク, Aynu Itak',
'Ajië – A’jie, Ajië, Houailou, Wai, Wailu',
'Akan – Akan, Fante, Twi',
'Albanian – Shqip, Shqiptar',
'Aleut – Unangam Tunuu, Унáҥам Тунý',
'Amdang – Sìmí Amdangtí',
'Amharic',
'Amoy – 廈門話 or 厦门话',
'Ancient Egyptian Language † – 𓂋𓏤𓈖𓆎𓅓𓏏𓊖',
'Angika',
'Apache – Ndéé',
'Apsaalooke – Apsaalooke',
'Arabic – العربية',
"Aragonese – l'Aragonés",
'Aramaic',
"Arapaho – Hinono'eitiitt",
'Armenian (Eastern) – Արևելահայերեն',
'Armenian (Western) – Արեւմտահայերէն',
'Armenian – Հայերեն',
'Arrernte – Arrernte Angkentye',
'Assamese',
'Asturian – Asturianu',
'Avar – МагIарул МацI',
'Avestan',
'Aymara – Aymar Aru',
'Azerbaijani – Azərbaycanca, آذربایجان دیلی',
'Baga † – Barka',
'Bai – 白语',
'Balinese',
'Balti – སྦལ་ཏིའི་སྐད་, بلتی',
'Bambara – Bamanankan',
'Bantu † – Narrow Bantu',
'Basa-Gumna † – Basa-Kaduna, Basa Kuta',
'Bashkir – башҡорт Теле, Başqort Tele',
'Basque – Euskara',
'Bassa – ɓasaá',
'Batak',
'Belarusian – Беларуская',
'Bemba – iciBemba',
'Bengali',
'Berber – Tamaziɣt, Tamazight',
'Berta – Gebeto or Wetawit',
'Bhojpuri بھوجپوري',
'Bislama – Bislama',
'Blackfoot',
'Bodo',
'Bosnian – Босански, Bosanski',
'Breton – Brezhoneg',
'Buginese',
'Buhid',
'Bulgarian – български език',
'Burmese',
'Cahuilla – Ivia',
'Cantonese – 廣東話',
'Carrier',
'Catalan – Català',
'Cayuga – Gayogo̱hó:nǫ’',
'Cebuano – Bisaya, Sinugboanon',
"Chamorro – Chamoru, Fino'Chamorro",
'Chechen – Нохчийн Mотт',
'Cherokee',
'Chewa – Nyanja',
'Cheyenne – Tsėhesenėstsestotse, Tsisinstsistots',
'Chhattisgarhi',
'Chickasaw – Chikasha',
'Chinese (Classical) – 古文 or 文言',
'Chinese, 漢語,, 華語, or 中文',
'Chipewyan - Dene Suline, Dëne Sųłiné',
"Choctaw – Chahta', Chahta Anumpa",
'Chuvash – Чӑвашла, Çăvaşla',
'Cimbrian – Zimbrisch',
'Comanche – Nʉmʉ Tekwapʉ',
'Coptic',
'Cornish – Kernewek, Kernowek',
'Corsican – Corsu',
'Cree',
'Croatian – Hrvatski',
"Cupeño † – Kupangaxwicham Pe'memelki",
'Czech – Český Jazyk, Čeština',
'Dakhini – دکنی',
'Dakota – Dakȟótiyapi',
'Dalecarlian – Dalmål',
'Danish – Dansk',
'Dargwa – Дарган Mез',
'Dari – فارسی, دری, دريلو, or Yazdi',
'Dhivehi ',
'Drehu – Dehu, Lifou, Lifu, Qene Drehu',
'Dungan – 回族语言, Xуэйзў йүян',
'Dutch – Nederlands',
'Dzongkha',
'Egyptian Arabic † – اللغة المصرية العامية',
'English – English',
'Erzya – Эрзянь Kель',
'Esperanto – Esperanto',
'Estonian – Eesti',
'Evenki – Эвэды̄ турэ̄н',
'Ewe – Èʋe, Èʋegbe',
'Eyak – I•ya•q',
'Faroese – Føroyskt',
'Fiji Hindi – Fiji Baat',
'Fijian – Na vosa vaka–Viti, Vakaviti',
'Filipino – Wikang Filipino',
'Finnish – Suomi',
'Fon – Fon gbè, Fɔngbè',
'French – Français',
'Frisian (North) – Noordfreesk',
'Frisian (Saterland) – Seeltersk',
'Frisian (West) – Frysk',
'Friulian – Furlan',
'Fula – Fulfulde, Pulaar, Pular',
'Fur – For',
'Fuzhou – 平話 or 福州話',
'Ga – Gã',
'Galician – Galego',
'Gan – 語',
"Ge'ez ",
'Georgian – ქართული',
'German – Deutsch',
'Gikuyu – Gĩkũyũ',
'Gilbertese – Taetae ni Kiribati',
'Godoberi – ГъибдилӀи Mицци, Ɣibdiƛi Micci',
'Gothic † – 𐌲𐌿𐍄𐌹𐍃𐌺',
'Greek – Ελληνικά',
'Greenlandic – Kalaallisut',
"Guaraní – Avañe'ẽ or Javy ju",
'Gujarati ',
'Gumuz – Bega',
'Gurung ',
"Gwich'in – Gwich'in",
'Haida – Xaat Kíl',
'Hainanese – 海南話',
'Haitian Creole – Kreyòl Ayisyen',
'Hakka – 客家話, 客家话',
'Harari ',
'Hausa – حَوْسَ',
'Hawaiian – ʻŌlelo Hawaiʻi',
'Hazāragī – هزارگی',
'Hebrew – עברית',
'Herero – Otjiherero',
'Himba – Omuhimba, Simba',
'Hindi',
'Hindustani – ہندوستانی,',
'Hiri Motu – Hiri Motu',
'Hmong – lol Hmongb, lus Hmoob, lug Moob',
'Hokkien – 福佬話',
'Hopi – Hopilàvayi or Hopílavayi',
'Hungarian – Magyar',
'Icelandic – Íslenska',
'Ido – Ido',
'Igbo – Asụsụ Igbo',
'Ik – Icetot',
'Ilocano – Iloko, Pagsasao nga Iloko',
'Indonesian – Bahasa Indonesia',
'Ingush – ГӀалгӀай мотт',
'Interlingua – Interlingua',
'Inuktitut',
'Inupiat – Iñupiatun',
'Irish – Gaeilge',
"Isthmus Nahuatl – Mela'tájtol",
'Italian – Italiano',
'Japanese – 日本語',
'Javanese',
'Judeo-Spanish – גֿודֿיאו–איספאנייול, Ladino',
'Jutish – Jydsk',
'Jèrriais – Jèrriais',
'Kabardian – Kъэбэрдеибзэ',
'Kabyle – شئعم',
'Kaingang – Kanhgág',
'Kannada',
'Kanuri – Kanuri',
'Karakalpak – Қарақалпақ тили, Qaraqalpaq tili',
'Karamojong – ŋaKaramojoŋ or ŋaKarimojoŋ',
'Karelian – Karjalan Kieli',
'Kashmiri – كٲشُر, Kạ̄šur, Koshur',
'Kashubian – Kaszëbsczi Jãzëk',
'Kazakh – Қазақ Tілі',
'Kelantanese Malay – بهاس ملايو كلنتن or Baso Kelate',
'Kendeje – Kendeje',
'Khakas – Хакас Tілі',
'Khmer',
'Khoekhoe – Khoekhoegowab',
'Khowar – کھوار',
'Kinyarwanda – Ikinyarwanda or Runyarwanda',
'Kiribati – Taetae Ni Kiribati',
'Konkani Konknni',
'Korean',
'Kuliak – Rub',
'Kumyk – Къумукъ Tил',
'Kurdish (Southern) – کوردی خوارین, Kurdîy Xwarîn',
'Kurdish – Kurdí, کوردی, or K’öрди',
'Kurmanji – Kurmancî, کورمانجی‎',
'Kutchi – کچھی or કચ્છી',
'Kwadi † – !Kwa/tse',
'Kwanyama – Oshikwanyama',
'Ladakhi',
'Ladin – Ladin',
'Lakota – Lakȟótiyapi',
'Lao',
'Latin – Lingua Latīna',
'Latvian – Latviešu',
'Laz – ლაზური ნენა',
'Leonese – Llïonés',
'Lepcha',
'Limbu',
'Limburgish – Lèmburgs',
'Lingala – Lingála',
'Lisu – ꓡꓲ–ꓢꓴ or ꓡꓲꓢꓴ',
'Lithuanian – Lietuvių',
'Livonian – Līvõ Kēļ or Rāndakēļ',
'Low German – Plattdüütsch',
'Low Prussian Dialect – Niederpreußisch',
'Luba-Kasai – Tshiluba',
'Luganda – Luganda, LùGáànda, Oluganda',
"Luiseño – Cham'teela",
'Luo – Kavirondo or Dholuo',
'Luri – لری or Lori',
'Luxembourgish – Lëtzebuergesch',
'Maasai – ɔl Maa',
'Macedonian – Mакедонски',
'Magahi',
'Magar',
'Maithili',
'Makassarese – Basa Mangkasara',
'Malagasy – Malagasy',
'Malay – بهاس ملايو or Bahasa Melayu',
'Malayalam',
'Maltese – Malti',
'Manchu',
'Mandarin – 國語',
'Manx – Gaelg',
'Marathi',
'Marshallese – Ebon, Kajin M̧ajeļ, Kajin Majõl',
'Masalit – kana masara',
'Meitei',
'Meänkieli – Meänkieli',
'Miami-Illinois – Myaamia',
'Michoacán Nahuatl – Pómaro Nahuatl',
'Min Bei – 闽北语',
'Min Dong – 閩東語',
'Min Nan – 閩南語 or 闽南语',
'Min Zhong – 闽中话',
'Min – 閩語',
'Mon်',
'Mongolian – Монгол Хэл',
'Montenegrin – crnogorski, црногорски',
'Monégasque – Munegascu',
'Muscogee Creek – Mvskoke, Mvskokē',
'Musgu – Mulwi',
'Muskum † – Muzuk',
'Māori – te Reo Māori',
'Nagumi † – Gong or Ngong',
'Nahuatl – Māsēwallahtōlli, Mexicano, or Nāhuatlahtōlli',
'Navajo – Diné bizaad',
'Ndyuka – Ndyuka.png',
'Nepal Bhasa',
'Nepali',
'Ngbee † – Lingbee',
'Ningbo – 寧波閒話',
'Northern Thai',
'Norwegian – Norsk',
'Nuosu',
"Nyangia – Nyang'i",
'Occidental – Interlingue',
'Occitan – Occitan',
'Odia',
'Ojibwe',
'Okinawan Japanese – ウチナーヤマトゥグチ',
'Old Church Slavonic † – Словѣ́ньскъ Ѩзꙑ́къ',
'Old English † – Anglisc, Ænglisc, Englisc',
'Omotik † – Laamoot',
'Pahari',
'Palula – پالولہ',
'Pashto – پښتو',
'Pattani Malay – بهاس جاوي, Bahasa Jawi ี',
'Persian – فارسی',
'Phoenician † – 𐤃𐤁𐤓𐤉𐤌 𐤊𐤍𐤏𐤍𐤉𐤌',
'Piman – Tepiman',
'Pipil – Náhuat or Nawat',
'Pitjantjatjara – Pitjantjatjara',
'Plautdietsch – Plautdietsch',
'Polish – Język polski, polski, or polszczyzna',
'Portuguese – Português',
'Pothohari – پوٹھوهاری or پوٹھواری',
'Pu-Xian Min – 興化話 or 莆仙話',
'Punjabi language, or پنجابی',
'Quanzhou – 泉州話',
'Quechuan – Runasimi',
'Raga – Hano',
'Rajasthani',
'Rohingya',
'Romani – Romani Ćhib',
'Romanian – Română',
'Romansh – Rumantsch',
'Russian – Русский',
'Rusyn – Русиньский Язык, Русиньска Бесїда',
'Ruthenian† – Руский Языкъ',
'Sami (Inari) – anarâškielâ',
'Sami (Kildin) – Кӣллт са̄мь кӣлл',
'Sami (Lule) – julevsámegiella',
'Sami (Northern) – davvisámegiella',
'Sami (Pite) – bidumsámegiella',
'Sami (Skolt) – sääʹmǩiõll, nuõrttsääʹmǩiõll',
'Sami (Southern) – åarjelsaemien gïele',
'Sami (Ume) – ubmejensámien giella',
'Samoan – Gagana Sāmoa',
'Sanskrit',
'Saraiki – سرائیکی',
'Sardinian – Sardu',
'Saurashtra',
'Scots – Scots, Scottis, Scots leid, Lallans',
'Scottish Gaelic – Gàidhlig',
'Serbian – Српски, Srpski',
'Serer – Seereer, Seereer–Siin',
'Seroa † – ǃGãǃne, ǁKuǁe',
'Shan',
'Shanghaiese – 上海',
'Sherpa language',
'Shona – Shona',
'Sicilian – Sicilianu',
'Sikkimese',
'Sindhi – سنڌي',
'Sinhala',
'Slovak – Slovenčina',
'Slovene – Slovenščina',
'Somali – اللغة الصومالية, Af–Soomaali',
'Sorani – سۆرانی, Soranî',
'Sotho – Sesotho',
'Spanish – Español',
'Stellingwarfs – Stellingwerfs',
'Sundanese',
'Swahili – Kiswahili',
'Swedish – Svenska',
'Swiss German – Schwyzerdütsch',
'Sylheti',
'Sámi (Ter) – Са̄мькӣлл, saa´mekiil',
'Tagalog – Wikang Tagalog',
"Tahitian – Reo Mā'ohi, Reo Tahiti",
'Tai Dam',
'Tai Khün',
'Tai Lü',
'Tai Nüa',
'Tamang',
'Tamil',
'Tangut †',
'Tatar – تاتارچا, Tatarça, Tатарча',
'Telugu',
'Teochew – 潮州話',
'Tepes – Soo',
'Teribe – Naso, Norteño, Quequexque, Teribe, Tiribi, or Térraba',
'Tetum – Lia-Tetun',
'Thai',
'Tibetan',
'Tigrinya',
'Tok Pisin – Tok Pisin',
'Tongan – Lea faka-Tonga',
'Tongva † – Gabrielino',
'Tsez – Цез Мец, Цезяс Мец',
'Tswana – Setswana',
'Tuareg – Tamahaq, Tamajaq, Tamasheq',
'Tulu',
'Tunica – Luhchi Yoroni',
'Turkish – Türkçe',
"Uduk – Tw'ampa or T'wampa",
'Ukrainian – Українська',
'Urdu – اُردُو',
'Uyghur – ئۇيغۇر تىلى',
'Uzbek – اوزبیک, Ўзбек, Oʻzbek',
'Valencian – Valencià',
'Venda – Tshivenḓa',
'Venetian – Vèneto',
'Vietnamese – Tiếng Việt Nam',
'Volapük – Volapük',
'Võro – Võro Kiil',
'Walloon – Walloon',
'Warlpiri – Warlpiri',
'Welsh – Cymraeg',
'West Frisian – Frysk',
'Wolof – Wolof',
'Wu – 吴方言',
'Xaracuu – Kanala, Xârâcùù',
'Xhosa – Xhosa',
'Xiang – 湘语',
'Xibe',
'Yapese – Yapese',
'Yiddish – ייִדיש ייִדיש',
'Yoruba – Èdè Yorùbá',
'Yue – 粵語, 粤语, 廣東話, or 广东话',
'Zhuang – 話僮',
'Zulu – Zulu',
'Äynu – ئەينۇ',
'ǂAkhoe – ǂAkhoe Haiǁom',
];