const List<String> titlesAsset = <String>[
'AA (Associate of Arts)',
'AAS (Associate of Applied Science)',
'AS (Associate of Science)',
'Abbess',
'Abbot',
'Acolyte',
'Agent',
'Alderman/Selectman',
'Almoner',
'Ambassador',
'Apostle',
'Archbishop',
'Archdeacon',
'Archdeaconess',
'Attaché',
'BA (Bachelor of Arts)',
'BArch (Bachelor of Architecture)',
'BBA (Bachelor of Business Administration)',
'BBiotech (Bachelor of Biotechnology)',
'BD / BDiv (Bachelor of Divinity)',
'BDS / BChD (Bachelor of Dental Surgery)',
'BDentTech (Bachelor of Dental Technology)',
'BDes (Bachelor of Design)',
'BEd (Bachelor of Education)',
'BEng (Bachelor of Engineering)',
'BEnvd (Bachelor of Environmental Design)',
'BFA (Bachelor of Fine Arts)',
'BM BCh (Bachelor of Medicine, Bachelor of Surgery)',
'BMath (Bachelor of Mathematics)',
'BMus (Bachelor of Music)',
'BN (Bachelor of Nursing)',
'BPhil (Bachelor of Philosophy)',
'BSBA (Bachelor of Science of Business Administration)',
'BSN (Bachelor of Science in Nursing)',
'BSW (Bachelor of Social Work)',
'BSc (Bachelor of Science)',
'B.Tech (Bachelor of Technology)',
'BTh / ThB (Bachelor of Theology)',
'BVSc (Bachelor of Veterinary Science)',
'Bishop',
'Boy Bishop',
'Brother',
'Burgess',
'Caliph',
'Canon',
'Cardinal',
'Cardinal Secretary of State',
'Catholicos',
'Chaplain',
"Chargé d'affaires",
'Coach',
'Constable',
'Councillor',
'D.D. (Doctor of Divinity)',
'D.Min. (Doctor of Ministry)',
'D.Mus. (Doctor of Music)',
'D.Prof (Doctor of Professional Studies)',
'D.Sc. (Doctor of Science)',
'DA (Doctor of Arts)',
'DBA (Doctor of Business Administration)',
'DC (Doctor of Chiropractic)',
'DDS (Doctor of Dental Surgery)',
'DFA (Doctor of Fine Arts)',
'DMA (Doctor of Musical Arts)',
'DMD (Doctor of Dental Medicine)',
'DO (Doctor of Osteopathic Medicine)',
'DPA (Doctor of Public Administration)',
'DPM (Doctor of Podiatric Medicine)',
'DPT (Doctor of Physical Therapy)',
'DVM (Doctor of Veterinary Medicine)',
'Dame',
'Deacon',
'Deaconess',
'Dean',
'Delegate',
'Deputy President',
'Docent (Doc.)',
'Doctor (Dr.)',
'Dom (D.)',
'Don (D.)',
'Dona (D.)',
'Donna (D.)',
'Ed.D. (Doctor of Education)',
'Elder',
'EngD or DEng (Doctor of Engineering)',
'Engineer',
'Envoy',
'Evangelist',
'Executive Vice President',
'Father (Fr.)',
'Foreign Secretary',
'Friar',
'General Secretary',
'Governor',
'High Priest',
'High Priestess',
'Honourable (Hon.)',
'JD (Doctor of Jurisprudence)',
'LL.D. (Doctor of Laws)',
'LL.M. (Master of Law)',
'LLB (Bachelor of Laws)',
'Lady Mayoress',
'Lieutenant Governor',
'Lord',
'Lord Archbishop',
'Lord High Almoner',
'Lord High Constable',
'Lord Mayor',
'Lord President of the Council',
'M. Des (Master of Design)',
'MA (Master of Arts)',
'MAL (Master of Liberal Arts)',
'MArch (Master of Architecture)',
'MB BChir (Bachelor of Medicine, Bachelor of Surgery)',
'MB BS (Bachelor of Medicine, Bachelor of Surgery)',
'MB ChB  (Bachelor of Medicine, Bachelor of Surgery)',
'MBA (Master of Business Administration)',
'MC (Master of Counselling)',
'MChem (Master in Chemistry)',
'MD (Doctor of Medicine)',
'MDS (Master of Dental Surgery)',
'MDiv (Master of Divinity)',
'MDrama (Master of Drama)',
'MET (Master of Educational Technology)',
'MEd (Master of Education)',
'MEng (Master of Engineering)',
'MFA (Master of Fine Arts)',
'MHA (Master of Healthcare Administration)',
'MHist (Master of History)',
'MLA (Master of Landscape Architecture)',
'MLitt Master of Letters)',
'MMath (Master of Mathematics)',
'MPA (Master of Public Administration)',
'MPH (Master of Public Health)',
'MPS (Master of Public Service)',
'MPharm (Master of Pharmacy)',
'MPhil (Master of Philosophy)',
'MPhys (Master of Physics)',
'MPl (Master of Planning)',
'MRes (Master of Research)',
'MSBA - Master of Science in Business Analytics)',
'MSE (Master of Science in Engineering)',
'MSRE (Master of Science in Real Estate)',
'MSW (Master of Social Work)',
'MSc (Master of Science)',
'MScBMC (Master of Biomedical Communications)',
'MURP (Master of Urban and Regional Planning)',
'Magister ',
'Mayor',
'Mayoress',
'Member of Congress (MC)',
'Member of Parliament (MP)',
'Member of Provincial Parliament (MPP)',
'Member of Youth Parliament (MYP)',
'Member of the European Parliament (MEP)',
'Member of the House of Assembly (MHA)',
'Member of the House of Keys (MHK)',
'Member of the House of Representatives (Rep.)',
'Member of the Legislative Assembly (MLA)',
'Member of the Legislative Council (MLC)',
'Member of the National Assembly (MNA)',
'Member of the Scottish Parliament (MSP)',
'Member of the Scottish Youth Parliament (MSYP)',
'Metropolitan Bishop',
'Minister',
'Monsignor',
'Mother',
'Mother Superior',
'ND (National Diploma)',
'Nurse',
'O.D. (Doctor of Optometry)',
'Pastor',
'Patriarch',
'Ph.D. / D.Phil. (Doctor of Philosophy)',
'Pharm.D. (Doctor of Pharmacy)',
'Pope',
'Prefect',
'Prelate',
'Premier',
'Presbyter',
'President',
'Priest',
'Priestess',
'Primate',
'Prince Bishop',
'Professional Engineer',
'Professional Nurse',
'Professor (Prof.)',
'Prophet',
'Provost',
'PsyD (Doctor of Psychology)',
'Reader',
'Registered Engineer',
'Registered Nurse (RN)',
'Representative',
'Reverend',
'Reverend Mother',
'Right Honourable (Rt. Hon.)',
'S.T.M. (Master of Sacred Theology)',
'STB (Bachelor of Sacred Theology)',
'Secretary',
'Secretary of State',
'Senator',
'Senior Constable',
'Sir',
'Sister',
'Speaker',
'Speaker of the House of Keys (SHK)',
'Speaker of the House of Representatives (SHR)',
'Teacher',
'Ter',
'Th.D. (Doctor of Theology)',
'ThM (Master of Theology)',
'Vicar',
'Vice President',
'Youth Councillor (YC)',
'Diploma de Estudios Avanzados',
'Diploma mill',
'Diploma of Biblical Studies',
'Diploma of Education',
'Diploma of Imperial College',
'Diploma of Journalism',
'Diploma in Computer Science',
'Diploma in Engineering',
'High school diploma',
'Postgraduate Diploma in Education',
'Professional Graduate Diploma in Education',
];
