//TODO: A list of university courses.

const List<String> fullUniversityCoursesAsset = [
'Accountancy',
'Accounting & Finance',
'Acturial Science',
'Adult Education & Extra-Mural Studies',
'Aeronautical & Manufacturing Engineering',
'Agricultural & Bioresources Engineering',
'Agricultural Economics',
'Agricultural Extension',
'Agriculture',
'Agriculture & Forestry',
'Agronomy',
'American Studies',
'Anatomy',
'Anatomy & Physiology',
'Anesthesia',
'Animal Health & Production',
'Animal Science',
'Anthropology',
'Arabic & Islamic Studies',
'Archaeology',
'Archeology & Tourism',
'Architecture',
'Art & Design',
'Arts Education',
'Aural & Oral Sciences',
'Banking & Finance',
'Biochemistry',
'Biological Sciences',
'Botany',
'Building',
'Business & Management Studies',
'Business Administration',
'Business Management',
'Cell Biology & Genetics',
'Celtic Studies',
'Chemical Engineering',
'Chemical Pathology',
'Chemistry',
'Child Dental Health',
'Christian Religious Studies',
'Civil Engineering',
'Classics & Ancient History',
'Clinical Pharmacy & Pharmacy Management',
'Commercial & Property Law',
'Communication & Media Studies',
'Community Medicine',
'Complementary Medicine',
'Computer Engineering',
'Computer Science',
'Counselling',
'Creative Writing',
'Criminology',
'Crop Science',
'Dentistry',
'Department of Pharmacology & Toxicology',
'Dermatology',
'Drama, Dance & Cinematics',
'East & South Asian Studies',
'Economics',
'Education',
'Education & Accountancy',
'Education & Biology',
'Education & Chemistry',
'Education & Computer Science',
'Education & Economics',
'Education & English Language',
'Education & French',
'Education & Geography/Physics',
'Education & Mathematics',
'Education & Physics',
'Education & Political Science',
'Education & Religious Studies',
'Education & Social Science',
'Educational / Psychology Guidance & Counselling',
'Educational Foundations',
'Electrical & Electronic Engineering',
'Electrical Engineering',
'Electronic Engineering',
'English',
'English & Literary Studies',
'Estate Management',
'Fashion',
'Film Making',
'Fine & Applied Arts (Creative Arts)',
'Fisheries',
'Food Science',
'Food Science & Technology',
'Foreign Languages & Literature',
'Forensic Science',
'Forest Resources Management (Forestry)',
'French',
'General Engineering',
'Geography',
'Geography & Environmental Sciences',
'Geoinformatics & Surveying',
'Geology',
'Geophysics',
'German',
'Health & Physical Education',
'Health Administration & Management',
'Hematology & Immunology',
'History',
'History & International Studies',
'History of Art, Architecture & Design',
'Home Science, Nutrition & Dietetics',
'Hospitality & Tourism',
'Hospitality, Leisure, Recreation & Tourism',
'Iberian Languages/Hispanic Studies',
'Igbo Linguistics',
'Industrial Relations & Personnel Management',
'Insurance',
'International & Jurisprudence',
'Italian',
'Land & Property Management',
'Law',
'Librarianship & Information Management',
'Library & Information Science',
'Linguistics',
'Linguistics & Nigerian Languages',
'Marine Biology',
'Marine Engineering',
'Marketing',
'Mass Communication (Communication & Language Arts)',
'Materials Technology',
'Mathematics',
'Mechanical Engineering',
'Medical Biochemistry',
'Medical Laboratory Sciences',
'Medical Microbiology',
'Medical Radiography & Radiological Sciences',
'Medical Rehabilitation',
'Medical Technology',
'Medicine',
'Metallurgical & Materials Engineering',
'Microbiology',
'Middle Eastern & African Studies',
'Morbid Anatomy',
'Music',
'Nursing',
'Nursing Sciences',
'Obstetrics & Gynecology',
'Occupational Therapy',
'Ophthalmology',
'Optometry, Ophthalmology & Orthoptics',
'Oral & Maxillofacial Surgery',
'Otolaryngology',
'Pediatrics',
'Petroleum & Gas Engineering',
'Pharmaceutical Chemistry & Industrial Pharmacy',
'Pharmaceutical Technology & Industrial Pharmacy',
'Pharmaceutics',
'Pharmacognosy',
'Pharmacology & Pharmacy',
'Pharmacology & Therapeutics',
'Philosophy',
'Physics',
'Physics & Astronomy',
'Physiology',
'Physiotherapy',
'Political Science',
'Politics',
'Preventive Dentistry',
'Private & Public Law',
'Production & Industrial Engineering',
'Psychological Medicine',
'Psychology',
'Public Administration & Local Government',
'Pure & Industrial Chemistry',
'Quantity Surveying',
'Radiation Medicine',
'Religion',
'Restorative Dentistry',
'Robotics',
'Russian & East European Languages',
'Science Education',
'Social Policy',
'Social Sciences Education',
'Social Work',
'Sociology',
'Sociology/Anthropology',
'Soil Science',
'Sports Science',
'Statistics',
'Structural Engineering',
'Surgery',
'Systems Engineering',
'Theatre & Film Studies',
'Theology & Religious Studies',
'Town & Country Planning & L&scape Design',
'Urban & Regional Planning',
'Veterinary Anatomy',
'Veterinary Medicine',
'Veterinary Obstetrics & Reproductive Diseases',
'Veterinary Parasitology & Entomology',
'Veterinary Pathology & Microbiology',
'Veterinary Physiology/Pharmacology',
'Veterinary Public Health & Preventive Medicine',
'Veterinary Surgery',
'Veterinary Teaching Hospital',
'Vocational Teacher Education (Technical Education)',
'Youth Work',
'Zoology',
];
